/* ============================================================
   myvocab — Example Sentences
   Kalit: inglizcha so'zning kichik harfdagi shakli (words.js va
   verbs.js bilan bir xil kalit maydoni — bir so'z ikkalasida
   uchrasa, gap ham umumiy bo'ladi).

   Format:  "key": [ inglizcha gap, o'zbekcha tarjima, ruscha tarjima ]

   Gap yozilmagan so'z kartochkada shunchaki gapsiz ko'rinadi —
   hech narsa buzilmaydi, to'ldirish bosqichma-bosqich boradi.
   ============================================================ */
const SENTENCES = {

  /* ═══════════ 01.08.2026 · 6 C / 6 D ═══════════ */
  "miss": ["I missed the bus and had to walk home.", "Avtobusni o'tqazib yubordim va uyga piyoda ketdim.", "Я пропустил автобус и пошёл домой пешком."],
  "grass": ["The children were playing on the green grass.", "Bolalar yashil maysada o'ynashardi.", "Дети играли на зелёной траве."],
  "paw": ["The cat hurt its paw on a stone.", "Mushuk tosh ustida panjasini og'ritdi.", "Кошка поранила лапу о камень."],
  "tent": ["Our tent is big enough for four people.", "Chodirimiz to'rt kishiga yetarli darajada katta.", "Наша палатка достаточно большая для четверых."],
  "climb": ["It took them six hours to climb the mountain.", "Tog'ga tirmashib chiqish ularga olti soat vaqt oldi.", "Подъём на гору занял у них шесть часов."],
  "feed": ["Don't forget to feed the dog before you leave.", "Ketishdan oldin itni ovqatlantirishni unutmang.", "Не забудь покормить собаку перед уходом."],
  "keep": ["I keep my documents in this drawer.", "Hujjatlarimni shu tortmada saqlayman.", "Я храню документы в этом ящике."],
  "rely": ["You can rely on him, he never lies.", "Unga ishonsangiz bo'ladi, u hech qachon yolg'on gapirmaydi.", "На него можно положиться, он никогда не врёт."],
  "safety": ["Safety comes first in the mountains.", "Tog'da xavfsizlik birinchi o'rinda turadi.", "В горах безопасность на первом месте."],
  "climber": ["The climber reached the top before sunset.", "Alpinist quyosh botishidan oldin cho'qqiga yetdi.", "Альпинист достиг вершины до заката."],
  "disappear": ["The keys disappeared from the table.", "Kalitlar stol ustidan yo'qolib qoldi.", "Ключи исчезли со стола."],
  "identify": ["The police could not identify the man on the video.", "Politsiya videodagi odamni aniqlay olmadi.", "Полиция не смогла опознать человека на видео."],
  "vehicle": ["No vehicles are allowed in the old town.", "Eski shaharga transport vositalari kiritilmaydi.", "В старый город въезд транспорта запрещён."],
  "camp": ["We put up our camp near the river.", "Biz daryo yonida oromgohimizni qurdik.", "Мы разбили лагерь у реки."],
  "solve": ["It took me an hour to solve this problem.", "Bu masalani hal qilishga bir soat ketdi.", "На решение этой задачи у меня ушёл час."],
  "possession": ["The house came into his possession last year.", "Uy o'tgan yili uning egaligiga o'tdi.", "Дом перешёл в его владение в прошлом году."],
  "notice": ["I noticed a mistake on the first page.", "Birinchi sahifada xatoni sezib qoldim.", "Я заметил ошибку на первой странице."],
  "path": ["A narrow path goes through the forest.", "O'rmon orasidan tor yo'l o'tadi.", "Через лес идёт узкая тропинка."],
  "put up the tent": ["It started to rain before we put up the tent.", "Chodir qurishimizdan oldin yomg'ir boshlandi.", "Дождь начался раньше, чем мы поставили палатку."],
  "complain": ["He always complains about the weather.", "U doim ob-havodan shikoyat qiladi.", "Он всегда жалуется на погоду."],
  "nightmare": ["The child woke up after a nightmare.", "Bola dahshatli tushdan keyin uyg'onib ketdi.", "Ребёнок проснулся после страшного сна."],
  "count": ["Let me count the money again.", "Pulni yana bir marta sanay.", "Дай я ещё раз посчитаю деньги."],
  "guess": ["Can you guess how old he is?", "U necha yoshda ekanini taxmin qila olasizmi?", "Можешь угадать, сколько ему лет?"],

  /* ═══════════ 03.08.2026 · 6 E ═══════════ */
  "movement": ["The camera notices any movement in the room.", "Kamera xonadagi har qanday harakatni sezadi.", "Камера замечает любое движение в комнате."],
  "survival": ["Water is the key to survival in the desert.", "Cho'lda omon qolishning kaliti — suv.", "Вода — ключ к выживанию в пустыне."],
  "rainforest": ["Thousands of birds live in the rainforest.", "Tropik o'rmonda minglab qushlar yashaydi.", "В тропическом лесу живут тысячи птиц."],
  "shortcut": ["We took a shortcut through the park.", "Biz park orqali qisqa yo'ldan yurdik.", "Мы срезали путь через парк."],
  "field": ["The farmer works in the field all day.", "Dehqon kun bo'yi dalada ishlaydi.", "Фермер работает в поле весь день."],
  "workmate": ["My workmate helped me finish the report.", "Hamkasbim hisobotni tugatishga yordam berdi.", "Коллега помог мне закончить отчёт."],
  "tree trunk": ["He sat down on a thick tree trunk.", "U yo'g'on daraxt tanasiga o'tirdi.", "Он сел на толстый ствол дерева."],
  "crawl": ["The baby learned to crawl at seven months.", "Chaqaloq yetti oyligida emaklashni o'rgandi.", "Малыш научился ползать в семь месяцев."],
  "bush": ["A small bird was hiding in the bush.", "Butada kichkina qush yashirinib turardi.", "В кусте пряталась маленькая птичка."],
  "rest": ["Let's rest for ten minutes.", "Kelinglar, o'n daqiqa dam olaylik.", "Давайте отдохнём десять минут."],
  "lucky": ["You are lucky to have such good friends.", "Bunday yaxshi do'stlaringiz borligi uchun omadlisiz.", "Тебе повезло, что у тебя такие хорошие друзья."],
  "surface": ["The surface of the table was wet.", "Stolning yuzasi ho'l edi.", "Поверхность стола была мокрой."],

  /* ═══════════ 03.08.2026 · 6 F ═══════════ */
  "strange": ["I heard a strange noise in the kitchen.", "Oshxonada g'alati ovoz eshitdim.", "Я услышал странный шум на кухне."],
  "fiction": ["This story is pure fiction, not history.", "Bu hikoya sof uydirma, tarix emas.", "Эта история — чистая выдумка, а не история."],
  "traveller": ["The traveller wrote a book about Asia.", "Sayohatchi Osiyo haqida kitob yozdi.", "Путешественник написал книгу об Азии."],
  "share": ["Children should learn to share their toys.", "Bolalar o'yinchoqlarini bo'lishishni o'rganishlari kerak.", "Дети должны учиться делиться игрушками."],
  "myth": ["It is a myth that we use only ten percent of our brain.", "Miyamizning atigi o'n foizini ishlatamiz degani — afsona.", "То, что мы используем лишь десять процентов мозга, — миф."],
  "case": ["In that case, we should leave earlier.", "Unday holatda ertaroq chiqishimiz kerak.", "В таком случае нам стоит выйти раньше."],
  "prove": ["He could not prove that he was at home.", "U uyda bo'lganini isbotlay olmadi.", "Он не смог доказать, что был дома."],
  "giant": ["A giant wave hit the small boat.", "Ulkan to'lqin kichik qayiqqa urildi.", "Гигантская волна ударила по маленькой лодке."],
  "match": ["Match the words with the pictures.", "So'zlarni rasmlarga moslashtiring.", "Соотнесите слова с картинками."],
  "squid": ["A giant squid can grow up to ten metres.", "Ulkan kalmar o'n metrgacha o'sishi mumkin.", "Гигантский кальмар может вырасти до десяти метров."],
  "ancient": ["We visited an ancient city in Turkey.", "Biz Turkiyadagi qadimiy shaharga tashrif buyurdik.", "Мы посетили древний город в Турции."],
  "realise": ["I did not realise how late it was.", "Qanchalik kech bo'lganini tushunib yetmabman.", "Я не осознавал, как уже поздно."],
  "discover": ["Scientists discovered a new kind of fish.", "Olimlar baliqning yangi turini kashf etishdi.", "Учёные обнаружили новый вид рыбы."],
  "description": ["Her description of the man was very clear.", "Uning o'sha odam haqidagi tasviri juda aniq edi.", "Её описание мужчины было очень чётким."],
  "receive": ["I received your letter yesterday.", "Xatingizni kecha oldim.", "Я получил ваше письмо вчера."],
  "inform": ["Please inform me if the time changes.", "Vaqt o'zgarsa, menga xabar bering.", "Пожалуйста, сообщите мне, если время изменится."],
  "once": ["I met him only once, many years ago.", "Men uni ko'p yillar oldin faqat bir marta uchratganman.", "Я встречал его лишь однажды, много лет назад."],
  "appear": ["A man suddenly appeared at the door.", "Eshik oldida to'satdan bir odam paydo bo'ldi.", "В дверях внезапно появился мужчина."],
  "attack": ["Wild dogs sometimes attack sheep.", "Yovvoyi itlar ba'zan qo'ylarga hujum qiladi.", "Дикие собаки иногда нападают на овец."],
  "creature": ["Whales are the largest creatures in the sea.", "Kitlar dengizdagi eng katta tirik mavjudotlardir.", "Киты — самые большие существа в море."],
  "sailor": ["The old sailor told us about his journeys.", "Keksa dengizchi bizga sayohatlari haqida gapirib berdi.", "Старый моряк рассказал нам о своих путешествиях."],
  "scientist": ["The scientist worked on the project for ten years.", "Olim loyiha ustida o'n yil ishladi.", "Учёный работал над проектом десять лет."],
  "coast": ["We drove along the coast for two hours.", "Biz ikki soat davomida dengiz qirg'og'i bo'ylab yurdik.", "Мы ехали вдоль побережья два часа."],
  "fisherman": ["The fisherman caught three big fish.", "Baliqchi uchta katta baliq tutdi.", "Рыбак поймал трёх больших рыб."],
  "axe": ["He cut the wood with a heavy axe.", "U yog'ochni og'ir bolta bilan chopdi.", "Он рубил дрова тяжёлым топором."],
  "amazed": ["We were amazed by the view from the top.", "Cho'qqidan ko'ringan manzaradan hayratlandik.", "Мы были поражены видом с вершины."],
  "rarely": ["He rarely watches television.", "U kamdan-kam televizor ko'radi.", "Он редко смотрит телевизор."],
  "exist": ["Many people believe that ghosts exist.", "Ko'pchilik arvohlar mavjud deb ishonadi.", "Многие верят, что призраки существуют."],
  "habitat": ["The forest is the natural habitat of these birds.", "O'rmon — bu qushlarning tabiiy yashash muhiti.", "Лес — естественная среда обитания этих птиц."],
  "explorer": ["The explorer spent two years in Africa.", "Tadqiqotchi Afrikada ikki yil o'tkazdi.", "Исследователь провёл в Африке два года."],
  "violent": ["The film is too violent for children.", "Bu film bolalar uchun juda shafqatsiz.", "Фильм слишком жестокий для детей."],
  "bad-tempered": ["Our neighbour is a bad-tempered old man.", "Qo'shnimiz — badjahl chol.", "Наш сосед — раздражительный старик."],
  "complete": ["The evening was a complete success.", "Kecha to'liq muvaffaqiyat bo'ldi.", "Вечер был полным успехом."],
  "mystery": ["Nobody knows the answer; it is still a mystery.", "Javobni hech kim bilmaydi; bu hamon sir.", "Никто не знает ответа; это всё ещё загадка."],
  "soldier": ["His brother is a soldier in the army.", "Uning akasi armiyada askar.", "Его брат — солдат в армии."],
  "to be familiar with": ["I am familiar with this program.", "Men bu dastur bilan tanishman.", "Я знаком с этой программой."],
  "politician": ["The politician answered all the questions.", "Siyosatchi barcha savollarga javob berdi.", "Политик ответил на все вопросы."],
  "manage": ["She managed to finish the work on time.", "U ishni o'z vaqtida tugatishni uddaladi.", "Ей удалось закончить работу вовремя."],
  "skin": ["The sun is bad for your skin.", "Quyosh teriga zararli.", "Солнце вредно для кожи."],
  "later": ["I will call you later this evening.", "Bugun kechqurun keyinroq qo'ng'iroq qilaman.", "Я позвоню тебе позже вечером."],
  "relative": ["All our relatives came to the wedding.", "Barcha qarindoshlarimiz to'yga kelishdi.", "Все наши родственники пришли на свадьбу."],
  "pilot": ["The pilot landed the plane safely.", "Uchuvchi samolyotni xavfsiz qo'ndirdi.", "Пилот безопасно посадил самолёт."],
  "crash": ["My computer crashes every time I open this file.", "Bu faylni ochganimda kompyuterim har safar buziladi.", "Мой компьютер зависает каждый раз, когда я открываю этот файл."],
  "island": ["They spent a week on a small island.", "Ular kichik orolda bir hafta o'tkazishdi.", "Они провели неделю на маленьком острове."],
  "horrible": ["The weather was horrible all weekend.", "Dam olish kunlari ob-havo dahshatli edi.", "Всю неделю погода была ужасной."],
  "tongue": ["He burned his tongue on the hot tea.", "U tilini issiq choyda kuydirib oldi.", "Он обжёг язык горячим чаем."],
  "lizard": ["A small lizard ran across the wall.", "Kichkina kaltakesak devor bo'ylab yugurdi.", "Маленькая ящерица пробежала по стене."],
  "include": ["The price includes breakfast.", "Narx nonushtani o'z ichiga oladi.", "Цена включает завтрак."],
  "research": ["Her research is about children and sleep.", "Uning tadqiqoti bolalar va uyqu haqida.", "Её исследование посвящено детям и сну."],
  "find out": ["I want to find out what really happened.", "Aslida nima bo'lganini bilib olmoqchiman.", "Я хочу выяснить, что произошло на самом деле."],

  /* ═══════════ 06.08.2026 · 6 G ═══════════ */
  "relaxing": ["A hot bath is very relaxing after work.", "Ishdan keyin issiq vanna juda dam oldiradi.", "Горячая ванна очень расслабляет после работы."],
  "quiet": ["Please be quiet, the baby is sleeping.", "Iltimos, tinch bo'ling, chaqaloq uxlayapti.", "Пожалуйста, потише, ребёнок спит."],
  "warm": ["It was a warm evening in early May.", "May boshida iliq oqshom edi.", "Это был тёплый вечер в начале мая."],
  "beach": ["We spent the whole day on the beach.", "Biz kun bo'yi sohilda o'tirdik.", "Мы провели весь день на пляже."],
  "cloud": ["There is not a single cloud in the sky.", "Osmonda bitta ham bulut yo'q.", "На небе ни облачка."],
  "flower": ["He bought her a flower on the way home.", "U uyga kelayotib unga gul sotib oldi.", "По дороге домой он купил ей цветок."],
  "ground": ["The ground was still wet after the rain.", "Yomg'irdan keyin yer hali ham ho'l edi.", "Земля всё ещё была мокрой после дождя."],
  "moon": ["The moon was very bright last night.", "Kecha oy juda yorqin edi.", "Прошлой ночью луна была очень яркой."],
  "rock": ["A big rock was lying on the road.", "Yo'lda katta tosh yotardi.", "На дороге лежал большой камень."],
  "sand": ["The children were playing in the sand.", "Bolalar qumda o'ynashardi.", "Дети играли в песке."],
  "sea": ["The sea is very calm this morning.", "Bugun ertalab dengiz juda tinch.", "Море сегодня утром очень спокойное."],
  "sky": ["The sky turned red at sunset.", "Quyosh botganda osmon qizarib ketdi.", "На закате небо стало красным."],
  "stars": ["You can see thousands of stars in the village.", "Qishloqda minglab yulduzlarni ko'rish mumkin.", "В деревне можно увидеть тысячи звёзд."],
  "sunrise": ["We got up early to watch the sunrise.", "Quyosh chiqishini tomosha qilish uchun erta turdik.", "Мы встали рано, чтобы посмотреть восход."],
  "sunset": ["The photo was taken just after sunset.", "Surat quyosh botgandan keyin olingan.", "Фото сделано сразу после заката."],
  "tree": ["An old tree grows in front of our house.", "Uyimiz oldida qari daraxt o'sadi.", "Перед нашим домом растёт старое дерево."],
  "cold": ["Put on a jacket, it is cold outside.", "Kurtka kiying, tashqarida sovuq.", "Надень куртку, на улице холодно."],
  "hot": ["It was too hot to walk in the afternoon.", "Tushdan keyin yurish uchun juda issiq edi.", "Днём было слишком жарко, чтобы гулять."],
  "rainy": ["It was a cold and rainy morning.", "Sovuq va yomg'irli tong edi.", "Было холодное и дождливое утро."],
  "stormy": ["The sea is dangerous in stormy weather.", "Bo'ronli havoda dengiz xavfli.", "В штормовую погоду море опасно."],
  "windy": ["It is too windy for a picnic today.", "Bugun piknik uchun juda shamolli.", "Сегодня слишком ветрено для пикника."],
  "weather": ["What is the weather like in London?", "Londonda ob-havo qanday?", "Какая погода в Лондоне?"],
  "in general": ["In general, I agree with your plan.", "Umuman olganda, rejangizga qo'shilaman.", "В общем, я согласен с вашим планом."],
  "in the background": ["In the background you can see the mountains.", "Orqa fonda tog'larni ko'rishingiz mumkin.", "На заднем фоне видны горы."],
  "in the foreground": ["In the foreground there is a young girl.", "Oldingi fonda yosh qiz turibdi.", "На переднем плане — молодая девушка."],
  "in the distance": ["In the distance we saw a small village.", "Uzoqroqda kichik qishloqni ko'rdik.", "Вдали мы увидели маленькую деревню."],
  "at the bottom": ["Write your name at the bottom of the page.", "Ismingizni sahifaning pastki tomoniga yozing.", "Напишите имя внизу страницы."],
  "at the top": ["At the top of the picture there is a bird.", "Rasmning yuqori tomonida qush bor.", "В верхней части картины — птица."],
  "face": ["My window faces the garden.", "Derazam bog'ga qarab turadi.", "Моё окно выходит в сад."],
  "look up": ["He looked up and saw a plane.", "U tepaga qaradi va samolyotni ko'rdi.", "Он посмотрел наверх и увидел самолёт."],
  "look down": ["Don't look down, we are very high.", "Pastga qaramang, biz juda balandmiz.", "Не смотри вниз, мы очень высоко."],

  /* ═══════════ 06.08.2026 · 6 H ═══════════ */
  "postcard": ["She sent me a postcard from Italy.", "U menga Italiyadan pochta varaqasi yubordi.", "Она прислала мне открытку из Италии."],
  "adventure": ["The trip was a real adventure for us.", "Sayohat biz uchun haqiqiy sarguzasht bo'ldi.", "Поездка стала для нас настоящим приключением."],
  "holiday": ["We are going to Turkey for our summer holiday.", "Yozgi ta'tilga Turkiyaga boramiz.", "На летний отпуск мы едем в Турцию."],
  "activity": ["Swimming is my favourite activity in summer.", "Suzish — yozdagi eng sevimli mashg'ulotim.", "Плавание — моё любимое занятие летом."],
  "abseil": ["We learned how to abseil down the cliff.", "Biz qoyadan arqon bilan tushishni o'rgandik.", "Мы научились спускаться со скалы на верёвке."],
  "cycle": ["I cycle to work every morning.", "Har kuni ertalab ishga velosipedda boraman.", "Каждое утро я езжу на работу на велосипеде."],
  "explore": ["We spent the day exploring the old town.", "Kunni eski shaharni o'rganib chiqish bilan o'tkazdik.", "Мы провели день, исследуя старый город."],
  "trek": ["The trek to the lake takes four hours.", "Ko'lgacha piyoda sayohat to'rt soat davom etadi.", "Поход до озера занимает четыре часа."],
  "bungee-jump": ["He was afraid to bungee-jump from the bridge.", "U ko'prikdan arqon bilan sakrashdan qo'rqdi.", "Он боялся прыгать с моста на верёвке."],
  "go caving": ["We are going caving with a local guide.", "Biz mahalliy gid bilan g'orga boramiz.", "Мы идём в пещеру с местным гидом."],
  "kite-surfing": ["Kite-surfing is popular on this beach.", "Bu sohilda kaytsyorfing mashhur.", "Кайтсёрфинг популярен на этом пляже."],
  "watch wildlife": ["We got up at five to watch wildlife.", "Yovvoyi tabiatni tomosha qilish uchun beshda turdik.", "Мы встали в пять, чтобы понаблюдать за дикой природой."],
  "windsurf": ["You need strong wind to windsurf.", "Vindsyorfing uchun kuchli shamol kerak.", "Для виндсёрфинга нужен сильный ветер."],
  "hostel": ["We stayed in a cheap hostel near the station.", "Biz bekat yonidagi arzon yotoqxonada qoldik.", "Мы остановились в дешёвом хостеле у вокзала."],
  "campsite": ["The campsite was full in August.", "Avgustda lager joyi to'la edi.", "В августе кемпинг был переполнен."],
  "cliff": ["The house stands on a high cliff.", "Uy baland qoya ustida turibdi.", "Дом стоит на высокой скале."],
  "wish": ["I wish you good luck in your exam.", "Imtihoningizda omad tilayman.", "Желаю тебе удачи на экзамене."],
  "fabulous": ["We had a fabulous time in Rome.", "Rimda ajoyib vaqt o'tkazdik.", "Мы потрясающе провели время в Риме."],
  "arrangement": ["We made an arrangement to meet at six.", "Soat oltida uchrashishga kelishuv qildik.", "Мы договорились встретиться в шесть."],
  "appropriate": ["Jeans are not appropriate for an interview.", "Jinsi shim suhbat uchun to'g'ri kelmaydi.", "Джинсы не подходят для собеседования."],

  /* ═══════════ 08.08.2026 · 7 A ═══════════ */
  "digital": ["Everything is digital in this office.", "Bu ofisda hamma narsa raqamli.", "В этом офисе всё цифровое."],
  "equipment": ["All the kitchen equipment is new.", "Oshxonaning barcha jihozlari yangi.", "Всё кухонное оборудование новое."],
  "modern": ["They live in a modern flat in the centre.", "Ular markazdagi zamonaviy kvartirada yashaydi.", "Они живут в современной квартире в центре."],
  "item": ["Each item in the shop has a price.", "Do'kondagi har bir buyumning narxi bor.", "У каждого товара в магазине есть цена."],
  "charger": ["I forgot my phone charger at home.", "Telefon zaryadkamni uyda unutib qoldirdim.", "Я забыл зарядку от телефона дома."],
  "headphones": ["He listens to music with big headphones.", "U katta quloqchinlarda musiqa tinglaydi.", "Он слушает музыку в больших наушниках."],
  "keyboard": ["The keyboard of my laptop is broken.", "Noutbukimning klaviaturasi buzilgan.", "Клавиатура моего ноутбука сломана."],
  "memory stick": ["Save the file on a memory stick.", "Faylni fleshkaga saqlang.", "Сохрани файл на флешку."],
  "router": ["Turn the router off and on again.", "Routerni o'chirib, yana yoqing.", "Выключите роутер и включите снова."],
  "speakers": ["The speakers are too loud for this room.", "Kolonkalar bu xona uchun juda baland.", "Колонки слишком громкие для этой комнаты."],
  "tablet": ["My daughter draws on her tablet.", "Qizim planshetida rasm chizadi.", "Моя дочь рисует на планшете."],
  "webcam": ["Please turn on your webcam for the meeting.", "Yig'ilish uchun veb-kamerangizni yoqing.", "Пожалуйста, включите камеру для встречи."],
  "connect to": ["I cannot connect to the internet.", "Internetga ulana olmayapman.", "Я не могу подключиться к интернету."],
  "delete": ["Do not delete these photos.", "Bu suratlarni o'chirmang.", "Не удаляй эти фотографии."],
  "download": ["It takes two minutes to download the file.", "Faylni yuklab olish ikki daqiqa oladi.", "Скачивание файла занимает две минуты."],
  "enter": ["Enter your password and press OK.", "Parolingizni kiriting va OK ni bosing.", "Введите пароль и нажмите ОК."],
  "offer": ["They offered him a job in Dubai.", "Ular unga Dubayda ish taklif qilishdi.", "Ему предложили работу в Дубае."],
  "scan": ["Can you scan this document for me?", "Bu hujjatni skanerlab bera olasizmi?", "Можешь отсканировать мне этот документ?"],
  "surf the web": ["He surfs the web for hours every evening.", "U har kuni kechqurun soatlab internetda yuradi.", "Он часами сидит в интернете каждый вечер."],

  /* ═══════════ 08.08.2026 · 7 B ═══════════ */
  "upload": ["I uploaded the photos to the cloud.", "Suratlarni bulutga yukladim.", "Я загрузил фотографии в облако."],
  "conversation": ["We had a long conversation about work.", "Biz ish haqida uzoq suhbat qildik.", "У нас был долгий разговор о работе."],
  "flash drive": ["The flash drive holds sixty-four gigabytes.", "Fleshka oltmish to'rt gigabayt sig'imga ega.", "Флешка вмещает шестьдесят четыре гигабайта."],
  "speed": ["The internet speed here is very low.", "Bu yerda internet tezligi juda past.", "Скорость интернета здесь очень низкая."],
  "stand for": ["What does this abbreviation stand for?", "Bu qisqartma nimani anglatadi?", "Что означает это сокращение?"],
  "protect": ["A password protects your account.", "Parol hisobingizni himoya qiladi.", "Пароль защищает вашу учётную запись."],
  "shape": ["The table has an unusual shape.", "Stolning shakli g'ayrioddiy.", "У стола необычная форма."],
  "size": ["What size shoes do you wear?", "Poyabzalingiz o'lchami nechchi?", "Какой у вас размер обуви?"],
  "get online": ["I cannot get online in this village.", "Bu qishloqda onlayn bo'la olmayman.", "В этой деревне я не могу выйти в интернет."],
  "click": ["Click on the blue button to continue.", "Davom etish uchun ko'k tugmani bosing.", "Нажмите синюю кнопку, чтобы продолжить."],
  "button": ["He pressed the wrong button.", "U noto'g'ri tugmani bosdi.", "Он нажал не ту кнопку."],
  "press": ["Press Enter to send the message.", "Xabarni yuborish uchun Enter ni bosing.", "Нажмите Enter, чтобы отправить сообщение."],
  "return": ["They returned home late at night.", "Ular tunda kech uyga qaytishdi.", "Они вернулись домой поздно ночью."],
  "annoy": ["The loud music really annoys me.", "Baland musiqa jonimga tegadi.", "Громкая музыка меня очень раздражает."],
  "dream": ["My dream is to travel around the world.", "Orzuim — dunyo bo'ylab sayohat qilish.", "Моя мечта — путешествовать по миру."],
  "afford": ["We cannot afford a new car this year.", "Bu yil yangi mashinaga qurbimiz yetmaydi.", "В этом году мы не можем позволить себе новую машину."],
  "fall off": ["The boy fell off his bike.", "Bola velosipeddan yiqilib tushdi.", "Мальчик упал с велосипеда."],
  "nearly": ["I nearly missed the train this morning.", "Bugun ertalab poyezdni deyarli o'tqazib yuborayozdim.", "Сегодня утром я чуть не опоздал на поезд."],
  "give up": ["He gave up smoking two years ago.", "U ikki yil oldin chekishni tashladi.", "Он бросил курить два года назад."],
  "piece": ["Would you like a piece of cake?", "Bir parcha tort xohlaysizmi?", "Хочешь кусочек торта?"],

  /* ═══════════ 11.08.2026 · 7 C / 7 D ═══════════ */
  "instruction": ["Read the instructions before you start.", "Boshlashdan oldin ko'rsatmalarni o'qing.", "Прочитайте инструкцию перед началом."],
  "experience": ["She has ten years of experience in teaching.", "Uning o'qituvchilikda o'n yillik tajribasi bor.", "У неё десять лет опыта в преподавании."],
  "slow": ["My old computer is very slow.", "Eski kompyuterim juda sekin.", "Мой старый компьютер очень медленный."],
  "access": ["Students have free access to the library.", "Talabalar kutubxonaga bepul kira oladi.", "У студентов свободный доступ в библиотеку."],
  "lose": ["Be careful not to lose your passport.", "Pasportingizni yo'qotib qo'ymang.", "Осторожно, не потеряй паспорт."],
  "set up": ["It took an hour to set up the printer.", "Printerni sozlashga bir soat ketdi.", "Настройка принтера заняла час."],
  "remove": ["Please remove your shoes at the door.", "Iltimos, eshik oldida poyabzalingizni yeching.", "Пожалуйста, снимайте обувь у двери."],
  "install": ["I need to install this program again.", "Bu dasturni qaytadan o'rnatishim kerak.", "Мне нужно снова установить эту программу."],
  "turn on": ["Could you turn on the air conditioner?", "Konditsionerni yoqib yubora olasizmi?", "Не могли бы вы включить кондиционер?"],
  "cable": ["This cable is too short for my desk.", "Bu kabel stolim uchun juda kalta.", "Этот кабель слишком короткий для моего стола."],
  "follow": ["Follow me, I know the way.", "Menga ergashing, men yo'lni bilaman.", "Идите за мной, я знаю дорогу."],
  "restart": ["Try to restart your phone.", "Telefoningizni qayta ishga tushirib ko'ring.", "Попробуйте перезапустить телефон."],
  "sequence": ["The photos are in the wrong sequence.", "Suratlar noto'g'ri ketma-ketlikda.", "Фотографии идут в неправильной последовательности."],
  "order": ["Put the words in the correct order.", "So'zlarni to'g'ri tartibda joylashtiring.", "Расставьте слова в правильном порядке."],
  "mark": ["The teacher marked our tests yesterday.", "O'qituvchi kecha testlarimizni baholadi.", "Учитель вчера проверил наши тесты."],
  "stage": ["The first stage of the project is finished.", "Loyihaning birinchi bosqichi tugadi.", "Первый этап проекта завершён."],
  "power source": ["The laptop needs a power source.", "Noutbukka quvvat manbai kerak.", "Ноутбуку нужен источник питания."],
  "desktop": ["The file is on my desktop.", "Fayl ish stolimda turibdi.", "Файл лежит у меня на рабочем столе."],
  "drag": ["Drag the file into this folder.", "Faylni shu papkaga olib o'ting.", "Перетащите файл в эту папку."],
  "folder": ["Keep all your photos in one folder.", "Barcha suratlaringizni bitta papkada saqlang.", "Храните все фотографии в одной папке."],
  "cause": ["Heavy rain caused problems on the roads.", "Kuchli yomg'ir yo'llarda muammo keltirib chiqardi.", "Сильный дождь вызвал проблемы на дорогах."],
  "select": ["Select a file and click Open.", "Faylni tanlang va Ochish ni bosing.", "Выберите файл и нажмите «Открыть»."],
  "update": ["The app updates itself every week.", "Ilova har hafta o'zini yangilaydi.", "Приложение обновляется каждую неделю."],
  "film": ["They filmed the whole concert.", "Ular butun konsertni kinoga olishdi.", "Они сняли весь концерт."],
  "primary school": ["My son starts primary school in September.", "O'g'lim sentabrda boshlang'ich maktabga boradi.", "Мой сын идёт в начальную школу в сентябре."],
  "band": ["Their band plays every Friday night.", "Ularning guruhi har juma kechqurun chiqish qiladi.", "Их группа играет каждую пятницу вечером."],
  "eat out": ["We eat out once or twice a month.", "Biz oyiga bir-ikki marta tashqarida ovqatlanamiz.", "Мы едим вне дома раз или два в месяц."],
  "useless": ["This old phone is completely useless now.", "Bu eski telefon hozir mutlaqo foydasiz.", "Этот старый телефон теперь совершенно бесполезен."],
  "write down": ["Write down my number, please.", "Iltimos, raqamimni yozib qo'ying.", "Запишите, пожалуйста, мой номер."],

  /* ═══════════ 13.08.2026 · 7 E ═══════════ */
  "put on": ["Put on your coat, it is cold outside.", "Paltoyingizni kiying, tashqarida sovuq.", "Надень пальто, на улице холодно."],
  "back up": ["Always back up your files before an update.", "Yangilashdan oldin doim fayllaringizni zaxiralang.", "Всегда делайте резервную копию файлов перед обновлением."],
  "plug in": ["Plug in the printer and turn it on.", "Printerni ulang va yoqing.", "Подключите принтер и включите его."],
  "scan in": ["I scanned in all the old photos.", "Barcha eski suratlarni skaner qildim.", "Я отсканировал все старые фотографии."],
  "shut down": ["Please shut down the computer before you leave.", "Ketishdan oldin kompyuterni o'chiring.", "Пожалуйста, выключите компьютер перед уходом."],
  "turn off": ["Turn off the lights when you go out.", "Chiqayotganda chiroqlarni o'chiring.", "Выключай свет, когда выходишь."],
  "turn up": ["Could you turn up the volume a little?", "Ovozni bir oz balandroq qila olasizmi?", "Можешь сделать звук немного громче?"],
  "turn down": ["Turn down the music, the baby is sleeping.", "Musiqani pasaytiring, chaqaloq uxlayapti.", "Сделай музыку тише, ребёнок спит."],
  "type in": ["Type in your email address here.", "Elektron pochtangizni shu yerga yozing.", "Введите здесь свой адрес электронной почты."],
  "break down": ["Our car broke down on the way to Samarkand.", "Mashinamiz Samarqandga ketayotib buzilib qoldi.", "Наша машина сломалась по дороге в Самарканд."],
  "log off": ["Do not forget to log off from the computer.", "Kompyuterdan chiqishni unutmang.", "Не забудьте выйти из системы на компьютере."],
  "log on": ["You have to log on with your student number.", "Talaba raqamingiz bilan tizimga kirishingiz kerak.", "Нужно войти в систему со своим студенческим номером."],
  "loud": ["The television is too loud.", "Televizor juda baland.", "Телевизор слишком громкий."],
  "application": ["She sent an application for the new job.", "U yangi ish uchun ariza yubordi.", "Она отправила заявление на новую работу."],

  /* ═══════════ 13.08.2026 · 7 F ═══════════ */
  "cyberbullying": ["Schools must fight cyberbullying seriously.", "Maktablar kiber zo'ravonlikka jiddiy qarshi turishi kerak.", "Школы должны серьёзно бороться с кибербуллингом."],
  "mention": ["He mentioned your name in his speech.", "U nutqida sizning ismingizni eslatib o'tdi.", "Он упомянул ваше имя в своей речи."],
  "fit": ["These shoes do not fit me.", "Bu poyabzal menga mos kelmaydi.", "Эти туфли мне не подходят."],
  "raise money": ["They raised money for a new hospital.", "Ular yangi shifoxona uchun pul yig'ishdi.", "Они собрали деньги на новую больницу."],
  "gig": ["The band played a small gig in the park.", "Guruh parkda kichik konsert berdi.", "Группа дала небольшой концерт в парке."],
  "campaign": ["The campaign helped thousands of children.", "Kampaniya minglab bolalarga yordam berdi.", "Кампания помогла тысячам детей."],
  "viral": ["Her video went viral in two days.", "Uning videosi ikki kunda tez tarqalib ketdi.", "Её видео стало вирусным за два дня."],
  "power": ["The storm cut off the power for two hours.", "Bo'ron ikki soatga quvvatni uzib qo'ydi.", "Из-за бури электричество отключили на два часа."],
  "well-known": ["He is a well-known writer in our country.", "U mamlakatimizda taniqli yozuvchi.", "Он известный писатель в нашей стране."],
  "victim": ["The victim of the accident is in hospital.", "Baxtsiz hodisa qurboni shifoxonada.", "Пострадавший в аварии находится в больнице."],
  "huge": ["They live in a huge house near the lake.", "Ular ko'l yonidagi ulkan uyda yashaydi.", "Они живут в огромном доме у озера."],
  "fundraising": ["The school organised a fundraising concert.", "Maktab mablag' yig'ish konsertini uyushtirdi.", "Школа организовала благотворительный концерт."],
  "anti-bullying": ["Our school has a strong anti-bullying rule.", "Maktabimizda zo'ravonlikka qarshi qat'iy qoida bor.", "В нашей школе строгие правила против травли."],
  "charity": ["All the money goes to charity.", "Barcha pul xayriyaga ketadi.", "Все деньги идут на благотворительность."],
  "take place": ["The meeting will take place on Monday.", "Yig'ilish dushanba kuni o'tkaziladi.", "Встреча состоится в понедельник."],
  "kindness": ["Thank you for your kindness and help.", "Mehribonligingiz va yordamingiz uchun rahmat.", "Спасибо за вашу доброту и помощь."],
  "half": ["Half of the students were absent.", "Talabalarning yarmi kelmagan edi.", "Половина студентов отсутствовала."],
  "environment": ["Plastic is very bad for the environment.", "Plastik atrof-muhitga juda zararli.", "Пластик очень вреден для окружающей среды."],
  "celebrity": ["A famous celebrity opened the new shop.", "Yangi do'konni mashhur yulduz ochib berdi.", "Новый магазин открыла известная знаменитость."],

  /* ═══════════ 15.08.2026 · 7 G ═══════════ */
  "price": ["The price of this phone is too high for me.", "Bu telefonning narxi men uchun juda baland.", "Цена этого телефона для меня слишком высокая."],
  "look for": ["I am looking for my keys.", "Kalitlarimni qidiryapman.", "Я ищу свои ключи."],
  "popular": ["This song is very popular among students.", "Bu qo'shiq talabalar orasida juda mashhur.", "Эта песня очень популярна среди студентов."],
  "a bit": ["I am a bit tired today.", "Bugun bir oz charchadim.", "Я сегодня немного устал."],
  "debit card": ["Can I pay by debit card?", "Debit kartasi bilan to'lasam bo'ladimi?", "Могу я заплатить дебетовой картой?"],
  "correctly": ["You answered all the questions correctly.", "Siz barcha savollarga to'g'ri javob berdingiz.", "Вы правильно ответили на все вопросы."],
  "feature": ["My favourite feature of this phone is the camera.", "Bu telefonning eng yoqqan xususiyati — kamerasi.", "Моя любимая функция этого телефона — камера."],
  "battery life": ["This laptop has a very good battery life.", "Bu noutbukning batareyasi juda uzoq ishlaydi.", "У этого ноутбука очень хорошее время работы батареи."],
  "built-in 4g": ["The tablet has built-in 4G, so you do not need Wi-Fi.", "Planshetda 4G o'rnatilgan, shuning uchun Wi-Fi kerak emas.", "В планшете встроенный 4G, поэтому Wi-Fi не нужен."],
  "built-in webcam": ["Every modern laptop has a built-in webcam.", "Har bir zamonaviy noutbukda veb-kamera o'rnatilgan.", "В каждом современном ноутбуке есть встроенная веб-камера."],
  "memory card slot": ["This camera has two memory card slots.", "Bu kamerada ikkita xotira karta uyasi bor.", "У этой камеры два слота для карт памяти."],
  "motion sensor": ["The lights work with a motion sensor.", "Chiroqlar harakat sensori bilan ishlaydi.", "Свет работает от датчика движения."],
  "touchscreen": ["My old laptop does not have a touchscreen.", "Eski noutbukimda sensorli ekran yo'q.", "У моего старого ноутбука нет сенсорного экрана."],
  "wireless": ["We use a wireless keyboard in the office.", "Ofisda simsiz klaviatura ishlatamiz.", "В офисе мы используем беспроводную клавиатуру."],
  "wireless speakers": ["He bought wireless speakers for the party.", "U bazm uchun simsiz kolonka sotib oldi.", "Он купил беспроводные колонки для вечеринки."],
  "cash": ["Sorry, we do not accept cash here.", "Kechirasiz, bu yerda naqd pul qabul qilmaymiz.", "Извините, мы здесь не принимаем наличные."],
  "change": ["Keep the change, please.", "Qaytimni o'zingizga olib qoling.", "Оставьте сдачу себе."],
  "receipt": ["Keep the receipt if you want to change the shoes.", "Poyabzalni almashtirmoqchi bo'lsangiz, chekni saqlang.", "Сохраните чек, если хотите обменять обувь."],
  "suggest": ["I suggest we meet at seven.", "Soat yettida uchrashishni taklif qilaman.", "Предлагаю встретиться в семь."],
  "confirm": ["Please confirm your booking by email.", "Iltimos, bronni elektron pochta orqali tasdiqlang.", "Пожалуйста, подтвердите бронь по электронной почте."],
  "currency": ["What is the currency of Japan?", "Yaponiyaning valyutasi qanday?", "Какая валюта в Японии?"],
  "payment method": ["Choose your payment method on the next page.", "Keyingi sahifada to'lov usulini tanlang.", "Выберите способ оплаты на следующей странице."],

  /* ═══════════ 15.08.2026 · 7 H ═══════════ */
  "narrative": ["The film has a simple but strong narrative.", "Filmning hikoyasi oddiy, lekin kuchli.", "У фильма простой, но сильный сюжет."],
  "locked": ["The door was locked and nobody answered.", "Eshik qulflangan edi va hech kim javob bermadi.", "Дверь была заперта, и никто не отвечал."],
  "electronic device": ["Please switch off all electronic devices.", "Iltimos, barcha elektron qurilmalarni o'chiring.", "Пожалуйста, выключите все электронные устройства."],
  "afterwards": ["We had dinner and went to the cinema afterwards.", "Kechki ovqat qildik va keyin kinoga bordik.", "Мы поужинали, а потом пошли в кино."],
  "accept": ["He accepted the job without thinking.", "U ishni o'ylab o'tirmay qabul qildi.", "Он принял работу не раздумывая."],
  "error": ["There is an error in the third line.", "Uchinchi qatorda xato bor.", "В третьей строке есть ошибка."],
  "unfortunately": ["Unfortunately, we missed the last bus.", "Afsuski, biz oxirgi avtobusni o'tqazib yubordik.", "К сожалению, мы опоздали на последний автобус."],
  "amazingly": ["Amazingly, he finished the race first.", "Hayratlanarlisi, u poygani birinchi bo'lib tugatdi.", "Удивительно, но он финишировал первым."],
  "type": ["What type of music do you like?", "Qanday turdagi musiqani yoqtirasiz?", "Какой тип музыки тебе нравится?"],
  "swap": ["Let's swap places, I cannot see the board.", "Keling, joy almashaylik, doskani ko'ra olmayapman.", "Давай поменяемся местами, мне не видно доску."],
  "by accident": ["I deleted the photos by accident.", "Men suratlarni tasodifan o'chirib yubordim.", "Я случайно удалил фотографии."],
  "lend": ["Could you lend me your pen for a minute?", "Ruchkangizni bir daqiqaga berib tura olasizmi?", "Не одолжишь мне ручку на минуту?"],
  "safely": ["They arrived home safely late at night.", "Ular tunda kech uyga xavfsiz yetib kelishdi.", "Они благополучно добрались домой поздно ночью."],
  "in the end": ["In the end, we decided to stay at home.", "Oxir-oqibat, uyda qolishga qaror qildik.", "В конце концов мы решили остаться дома."],
  "set the scene": ["The first page sets the scene of the story.", "Birinchi sahifa hikoya sahnasini tayyorlaydi.", "Первая страница задаёт обстановку рассказа."],
  "recently": ["I have recently started learning English.", "Yaqinda ingliz tilini o'rganishni boshladim.", "Недавно я начал учить английский."],
  "comma": ["You need a comma after this word.", "Bu so'zdan keyin vergul kerak.", "После этого слова нужна запятая."],
  "quotation mark": ["Put the title in quotation marks.", "Sarlavhani qo'shtirnoq ichiga oling.", "Возьмите заголовок в кавычки."],
  "question mark": ["Do not forget the question mark at the end.", "Oxirida so'roq belgisini unutmang.", "Не забудьте вопросительный знак в конце."],
  "exclamation mark": ["He used three exclamation marks in one sentence.", "U bitta gapda uchta undov belgisi ishlatdi.", "Он поставил три восклицательных знака в одном предложении."],
  "particular": ["Is there any particular reason for this?", "Buning biror alohida sababi bormi?", "Есть ли для этого какая-то особая причина?"],
  "event": ["The concert was the event of the year.", "Konsert yilning eng katta voqeasi bo'ldi.", "Концерт стал событием года."],

  /* ═══════════ 18.08.2026 · 8 A / 8 B ═══════════ */
  "active": ["My grandfather is still very active at eighty.", "Bobom sakson yoshida ham juda faol.", "Мой дед в восемьдесят всё ещё очень активен."],
  "how often": ["How often do you go to the gym?", "Sport zaliga qancha vaqtda borasiz?", "Как часто ты ходишь в спортзал?"],
  "normally": ["I normally get up at half past six.", "Odatda soat olti yarimda turaman.", "Обычно я встаю в половине седьмого."],
  "team": ["Our team won the game three to one.", "Jamoamiz o'yinni uch-birga yutdi.", "Наша команда выиграла матч три-один."],
  "combat": ["Combat sports are popular among young people.", "Jang san'atlari yoshlar orasida mashhur.", "Боевые виды спорта популярны среди молодёжи."],
  "correct": ["Only one answer is correct.", "Faqat bitta javob to'g'ri.", "Правильный только один ответ."],
  "add": ["Add a little salt to the soup.", "Sho'rvaga ozgina tuz qo'shing.", "Добавьте в суп немного соли."],
  "fall over": ["He fell over and hurt his arm.", "U yiqilib tushdi va qo'lini og'ritdi.", "Он упал и повредил руку."],
  "injure": ["He injured his knee during the match.", "U o'yin davomida tizzasini shikastladi.", "Он повредил колено во время матча."],
  "score": ["He scored two goals in the second half.", "U ikkinchi bo'limda ikkita gol urdi.", "Он забил два гола во втором тайме."],
  "break a record": ["He broke a world record at the age of nineteen.", "U o'n to'qqiz yoshida jahon rekordini yangiladi.", "Он побил мировой рекорд в девятнадцать лет."],
  "take part": ["More than fifty runners took part in the race.", "Poygada ellikdan ortiq yuguruvchi qatnashdi.", "В забеге приняли участие более пятидесяти бегунов."],
  "competition": ["She won first place in the competition.", "U musobaqada birinchi o'rinni egalladi.", "Она заняла первое место в соревновании."],
  "support": ["My parents always support my decisions.", "Ota-onam doim qarorlarimni qo'llab-quvvatlaydi.", "Родители всегда поддерживают мои решения."],
  "supporter": ["Thousands of supporters were singing in the stadium.", "Stadionda minglab muxlislar qo'shiq aytardi.", "Тысячи болельщиков пели на стадионе."],

  /* ═══════════ 20.08.2026 · 8 C / 8 D ═══════════ */
  "prediction": ["His prediction about the weather was wrong.", "Uning ob-havo haqidagi bashorati noto'g'ri chiqdi.", "Его предсказание о погоде оказалось неверным."],
  "rock face": ["The climbers slowly went up the rock face.", "Alpinistlar qoya yuzasidan asta yuqoriga ko'tarildi.", "Альпинисты медленно поднимались по отвесной стене."],
  "rope": ["Hold the rope with both hands.", "Arqonni ikki qo'llab ushlang.", "Держите верёвку двумя руками."],
  "steep": ["The road to the village is very steep.", "Qishloqqa boradigan yo'l juda tikka.", "Дорога в деревню очень крутая."],
  "attempt": ["He passed the exam on his second attempt.", "U imtihondan ikkinchi urinishda o'tdi.", "Он сдал экзамен со второй попытки."],
  "progress": ["You have made good progress this month.", "Bu oyda yaxshi taraqqiyotga erishdingiz.", "В этом месяце вы добились хорошего прогресса."],
  "ambition": ["Her ambition is to become a doctor.", "Uning maqsadi — shifokor bo'lish.", "Её цель — стать врачом."],
  "possible": ["Is it possible to change the date?", "Sanani o'zgartirish mumkinmi?", "Можно ли изменить дату?"],
  "go down": ["Prices usually go down after the holidays.", "Narxlar odatda bayramlardan keyin pasayadi.", "Цены обычно снижаются после праздников."],
  "compete": ["Ten teams will compete for the cup.", "O'nta jamoa kubok uchun bellashadi.", "Десять команд будут бороться за кубок."],
  "delayed": ["Our flight was delayed by three hours.", "Reysimiz uch soatga kechiktirildi.", "Наш рейс задержали на три часа."],
  "earn": ["She earns enough to travel every year.", "U har yili sayohat qilishga yetarli pul ishlab topadi.", "Она зарабатывает достаточно, чтобы путешествовать каждый год."],
  "own": ["I would like to have my own office.", "O'zimning shaxsiy ofisim bo'lishini xohlardim.", "Я хотел бы иметь свой собственный офис."],

  /* ═══════════ 22.08.2026 · 8 E / 8 F ═══════════ */
  "beat": ["Our team beat them two to nil.", "Jamoamiz ularni ikki-nolga yengdi.", "Наша команда обыграла их два-ноль."],
  "cancer": ["Early treatment of cancer saves lives.", "Saratonni erta davolash hayot saqlaydi.", "Раннее лечение рака спасает жизни."],
  "title": ["I cannot remember the title of that book.", "O'sha kitobning sarlavhasini eslay olmayapman.", "Я не могу вспомнить название той книги."],
  "teenager": ["As a teenager he played in a band.", "O'smirlik chog'ida u guruhda chalgan.", "Подростком он играл в группе."],
  "treatment": ["The treatment lasted six months.", "Davolash olti oy davom etdi.", "Лечение длилось шесть месяцев."],
  "permission": ["You need permission to take photos here.", "Bu yerda surat olish uchun ruxsat kerak.", "Здесь нужно разрешение, чтобы фотографировать."],
  "independent": ["She has been independent since she was eighteen.", "U o'n sakkiz yoshidan beri mustaqil.", "Она независима с восемнадцати лет."],
  "homesickness": ["Homesickness is normal in the first month.", "Birinchi oyda uy sog'inchi tabiiy holat.", "Тоска по дому в первый месяц — это нормально."],
  "preparation": ["Preparation for the exam took two weeks.", "Imtihonga tayyorgarlik ikki hafta oldi.", "Подготовка к экзамену заняла две недели."],
  "route": ["This is the shortest route to the airport.", "Bu aeroportga eng qisqa yo'l.", "Это самый короткий маршрут до аэропорта."],
  "accommodation": ["The price includes flights and accommodation.", "Narx parvoz va turar joyni o'z ichiga oladi.", "Цена включает перелёт и проживание."],
  "darkness": ["We walked home in complete darkness.", "Biz uyga to'liq qorong'ulikda yurdik.", "Мы шли домой в полной темноте."],
  "donation": ["Every donation helps the children.", "Har bir ehson bolalarga yordam beradi.", "Каждое пожертвование помогает детям."],
  "achievement": ["Finishing the marathon was a great achievement.", "Marafonni tugatish katta yutuq bo'ldi.", "Финиш марафона стал большим достижением."],
  "arrange": ["I arranged a meeting for Friday.", "Juma kuniga uchrashuv uyushtirdim.", "Я организовал встречу на пятницу."],
  "converse": ["They conversed quietly in the corner.", "Ular burchakda ohista suhbatlashdi.", "Они тихо беседовали в углу."],
  "sadness": ["There was deep sadness in her eyes.", "Uning ko'zlarida chuqur qayg'u bor edi.", "В её глазах была глубокая грусть."],
  "happiness": ["Money does not always bring happiness.", "Pul har doim ham baxt keltirmaydi.", "Деньги не всегда приносят счастье."],
  "accommodate": ["The hotel can accommodate two hundred guests.", "Mehmonxona ikki yuz mehmonni joylashtira oladi.", "Отель может разместить двести гостей."],
  "achieve": ["She achieved all her goals this year.", "U bu yil barcha maqsadlariga erishdi.", "В этом году она достигла всех своих целей."],
  "dark": ["It gets dark early in winter.", "Qishda erta qorong'i tushadi.", "Зимой рано темнеет."],
  "donate": ["He donated a large sum to the hospital.", "U shifoxonaga katta summa ehson qildi.", "Он пожертвовал больнице крупную сумму."],
  "permit": ["The rules do not permit dogs in the park.", "Qoidalar parkda itlarga ruxsat bermaydi.", "Правила не разрешают собак в парке."],
  "prepare": ["I am preparing dinner for six people.", "Olti kishiga kechki ovqat tayyorlayapman.", "Я готовлю ужин на шесть человек."],
  "treat": ["Doctors treated him for two weeks.", "Shifokorlar uni ikki hafta davoladi.", "Врачи лечили его две недели."],
  "rude": ["It is rude to speak with your mouth full.", "Og'iz to'la gapirish qo'pollik.", "Невежливо говорить с полным ртом."],
  "suggestion": ["Thank you for your useful suggestion.", "Foydali taklifingiz uchun rahmat.", "Спасибо за ваше полезное предложение."],
  "argue": ["They often argue about small things.", "Ular tez-tez mayda narsalar ustida bahslashadi.", "Они часто спорят по мелочам."],
  "discuss": ["We will discuss the plan tomorrow.", "Rejani ertaga muhokama qilamiz.", "Мы обсудим план завтра."],
  "explain": ["Could you explain this rule again?", "Bu qoidani yana bir bor tushuntira olasizmi?", "Можете объяснить это правило ещё раз?"],
  "competitor": ["Her main competitor is from Kenya.", "Uning asosiy raqibi Keniyalik.", "Её главный соперник — из Кении."],
  "disability": ["The building is easy to use for people with a disability.", "Bino nogironligi bor odamlar uchun qulay.", "Здание удобно для людей с инвалидностью."],
  "blind": ["A blind man was crossing the street with a dog.", "Ko'r odam it bilan ko'chani kesib o'tayotgan edi.", "Слепой мужчина переходил улицу с собакой."],
  "accident": ["There was a bad accident on the main road.", "Asosiy yo'lda og'ir baxtsiz hodisa sodir bo'ldi.", "На главной дороге произошла серьёзная авария."],
  "hill": ["Their house stands on a small hill.", "Ularning uyi kichik tepalikda joylashgan.", "Их дом стоит на небольшом холме."],
  "disease": ["This disease is now easy to treat.", "Bu kasallikni endi davolash oson.", "Эту болезнь теперь легко лечить."],
  "noise": ["The noise from the street kept me awake.", "Ko'chadagi shovqin uxlashimga xalaqit berdi.", "Шум с улицы не давал мне уснуть."],
  "per": ["The car uses seven litres per hundred kilometres.", "Mashina yuz kilometrga yetti litr sarflaydi.", "Машина расходует семь литров на сто километров."],
  "wheelchair": ["He has been in a wheelchair since the accident.", "U baxtsiz hodisadan keyin nogironlar aravachasida.", "После аварии он передвигается в инвалидной коляске."],
  "nationality": ["What nationality is your teacher?", "O'qituvchingiz qaysi millat vakili?", "Какой национальности ваш учитель?"],
  "recent": ["In recent years the city has changed a lot.", "So'nggi yillarda shahar ancha o'zgardi.", "За последние годы город сильно изменился."],
  "brave": ["It was brave of you to say the truth.", "Haqiqatni aytganingiz jasorat edi.", "С твоей стороны было смело сказать правду."],

  /* ═══════════ 25.08.2026 · 8 G / 8 H ═══════════ */
  "negotiating": ["They spent all day negotiating the price.", "Ular kun bo'yi narx ustida muzokara olib borishdi.", "Они весь день вели переговоры о цене."],
  "high jump": ["She won the high jump with two metres.", "U balandlikka sakrashda ikki metr bilan g'olib chiqdi.", "Она выиграла прыжки в высоту с результатом два метра."],
  "long jump": ["He is training for the long jump.", "U uzoqqa sakrashga tayyorgarlik ko'ryapti.", "Он тренируется в прыжках в длину."],
  "pole vault": ["The pole vault is a difficult event.", "Tayoqda sakrash — qiyin tur.", "Прыжок с шестом — сложная дисциплина."],
  "relay": ["Our team came second in the relay.", "Jamoamiz estafetada ikkinchi o'rinni oldi.", "Наша команда заняла второе место в эстафете."],
  "shot put": ["He holds the school record in the shot put.", "U tosh otish bo'yicha maktab rekordini ushlab turibdi.", "Он держит школьный рекорд в толкании ядра."],
  "cross-country running": ["Cross-country running is hard in winter.", "Qishda mamlakat bo'ylab yugurish qiyin.", "Зимой бегать по пересечённой местности тяжело."],
  "discus": ["The discus flew almost sixty metres.", "Disk deyarli oltmish metr uchdi.", "Диск пролетел почти шестьдесят метров."],
  "hammer": ["He won a gold medal in the hammer.", "U bolg'a otishda oltin medal oldi.", "Он выиграл золото в метании молота."],
  "hurdles": ["She fell at the last hurdle.", "U oxirgi to'siqda yiqildi.", "Она упала на последнем барьере."],
  "javelin": ["The javelin landed near the line.", "Nayza chiziq yoniga tushdi.", "Копьё приземлилось у самой линии."],
  "fancy": ["Do you fancy a cup of tea?", "Bir piyola choy xohlaysizmi?", "Не хочешь чашку чая?"],
  "would rather": ["I would rather stay at home tonight.", "Bugun kechqurun uyda qolishni afzal ko'raman.", "Сегодня вечером я бы предпочёл остаться дома."],
  "too": ["This bag is too heavy for me.", "Bu sumka men uchun juda og'ir.", "Эта сумка для меня слишком тяжёлая."],
  "diving": ["Diving is my favourite summer sport.", "Suvga sho'ng'ish — yozdagi sevimli sportim.", "Дайвинг — мой любимый летний спорт."],
  "interact": ["Children learn by interacting with each other.", "Bolalar bir-biri bilan muloqot qilib o'rganadi.", "Дети учатся, взаимодействуя друг с другом."],
  "suppose": ["I suppose he is still at work.", "O'ylashimcha, u hali ishda.", "Полагаю, он ещё на работе."],
  "informal": ["The meeting was short and informal.", "Uchrashuv qisqa va norasmiy bo'ldi.", "Встреча была короткой и неформальной."],
  "reply": ["He did not reply to my message.", "U xabarimga javob bermadi.", "Он не ответил на моё сообщение."],
  "goggles": ["Do not swim without goggles in the pool.", "Basseynda ko'zoynaksiz suzmang.", "Не плавайте в бассейне без очков."],
  "helmet": ["Always wear a helmet when you cycle.", "Velosipedda yurganda doim shlem kiying.", "Всегда надевайте шлем, когда едете на велосипеде."],
  "running shoes": ["I need new running shoes for the marathon.", "Marafon uchun yangi yugurish oyoq kiyimi kerak.", "Мне нужны новые беговые кроссовки для марафона."],
  "wetsuit": ["The water is cold, take a wetsuit.", "Suv sovuq, suzish kostyumini oling.", "Вода холодная, возьмите гидрокостюм."],
  "bat": ["He hit the ball with a wooden bat.", "U to'pni yog'och bita bilan urdi.", "Он ударил по мячу деревянной битой."],
  "gloves": ["Put on your gloves, it is freezing.", "Qo'lqoplaringizni kiying, sovuq qattiq.", "Надень перчатки, очень холодно."],
  "net": ["The ball hit the net and stopped.", "To'p to'rga urilib to'xtadi.", "Мяч ударился о сетку и остановился."],
  "racket": ["My tennis racket is quite old.", "Tennis raketkam ancha eski.", "Моя теннисная ракетка довольно старая."],
  "apologise": ["He apologised for being late.", "U kechikkani uchun kechirim so'radi.", "Он извинился за опоздание."],

  /* ═══════════ 27.08.2026 · 9 A / 9 B ═══════════ */
  "attractive": ["She lives in an attractive old house.", "U jozibali eski uyda yashaydi.", "Она живёт в привлекательном старом доме."],
  "comfortable": ["This chair is very comfortable.", "Bu kursi juda qulay.", "Это кресло очень удобное."],
  "unusual": ["It is unusual for him to be late.", "Uning kechikishi noodatiy hol.", "Для него необычно опаздывать."],
  "furniture": ["We bought new furniture for the living room.", "Biz mehmonxona uchun yangi mebel sotib oldik.", "Мы купили новую мебель для гостиной."],
  "household": ["She does most of the household work.", "Uy xo'jaligi ishlarining ko'pini u qiladi.", "Большую часть домашней работы делает она."],
  "bath": ["I take a hot bath every evening.", "Har kuni kechqurun issiq vanna qabul qilaman.", "Каждый вечер я принимаю горячую ванну."],
  "bin": ["Please throw it in the bin.", "Iltimos, buni chelakka tashlang.", "Пожалуйста, выбрось это в ведро."],
  "blinds": ["Close the blinds, the sun is too bright.", "Jalyuzini yoping, quyosh juda yorqin.", "Закрой жалюзи, солнце слишком яркое."],
  "bookcase": ["The bookcase is full of old books.", "Kitob javoni eski kitoblarga to'la.", "Книжный шкаф полон старых книг."],
  "carpet": ["There is a red carpet in the hall.", "Zalda qizil gilam bor.", "В зале лежит красный ковёр."],
  "chest of drawers": ["Your socks are in the chest of drawers.", "Paypoqlaringiz tortmali shkafda.", "Твои носки в комоде."],
  "cooker": ["Be careful, the cooker is still hot.", "Ehtiyot bo'ling, gaz plitasi hali issiq.", "Осторожно, плита ещё горячая."],
  "cupboard": ["The cups are in the kitchen cupboard.", "Piyolalar oshxona shkafida.", "Чашки в кухонном шкафу."],
  "curtains": ["We need new curtains for the bedroom.", "Yotoqxona uchun yangi parda kerak.", "Нам нужны новые шторы в спальню."],
  "hi-fi": ["He bought an expensive hi-fi last year.", "U o'tgan yili qimmat magnitofon sotib oldi.", "В прошлом году он купил дорогой музыкальный центр."],
  "rug": ["There is a small rug next to the bed.", "Karavot yonida kichkina gilam bor.", "Рядом с кроватью лежит небольшой коврик."],
  "sink": ["Please wash the cups in the sink.", "Iltimos, piyolalarni rakovinada yuving.", "Пожалуйста, помойте чашки в раковине."],
  "sofa": ["The cat is sleeping on the sofa.", "Mushuk divanda uxlayapti.", "Кот спит на диване."],
  "stool": ["He sat on a high stool at the bar.", "U barda baland kursida o'tirdi.", "Он сел на высокий табурет у барной стойки."],
  "wardrobe": ["All her clothes are in the wardrobe.", "Uning barcha kiyimlari kiyim javonida.", "Вся её одежда в шкафу."],
  "washing machine": ["Our washing machine is broken again.", "Kir yuvish mashinamiz yana buzildi.", "Наша стиральная машина снова сломалась."],
  "just": ["I have just finished my homework.", "Uy vazifamni hozirgina tugatdim.", "Я только что закончил домашнее задание."],
  "basement": ["We keep our old books in the basement.", "Eski kitoblarimizni yerto'lada saqlaymiz.", "Мы храним старые книги в подвале."],
  "hall": ["Leave your shoes in the hall.", "Poyabzalingizni koridorda qoldiring.", "Оставьте обувь в прихожей."],
  "loft": ["There are old toys in the loft.", "Cherdakda eski o'yinchoqlar bor.", "На чердаке лежат старые игрушки."],
  "utility room": ["The washing machine is in the utility room.", "Kir yuvish mashinasi yordamchi xonada.", "Стиральная машина в подсобном помещении."],
  "scream": ["She screamed when she saw the spider.", "U o'rgimchakni ko'rib qichqirib yubordi.", "Она закричала, когда увидела паука."],
  "habit": ["Reading before bed is a good habit.", "Uxlashdan oldin kitob o'qish — yaxshi odat.", "Читать перед сном — хорошая привычка."],
  "emphasise": ["The teacher emphasised the importance of practice.", "O'qituvchi mashqning ahamiyatiga alohida urg'u berdi.", "Учитель подчеркнул важность практики."],

  /* ═══════════ 29.08.2026 · 9 C / 9 E ═══════════ */
  "residence": ["His main residence is in the capital.", "Uning asosiy turar joyi poytaxtda.", "Его основное место жительства — в столице."],
  "canteen": ["We usually have lunch in the canteen.", "Odatda tushlikni oshxonada qilamiz.", "Обычно мы обедаем в столовой."],
  "rent": ["They rent a small flat near the university.", "Ular universitet yonida kichik kvartira ijaraga olishgan.", "Они снимают маленькую квартиру рядом с университетом."],
  "expense": ["Travel expenses are paid by the company.", "Sayohat xarajatlarini kompaniya to'laydi.", "Командировочные расходы оплачивает компания."],
  "apart from": ["Apart from Sunday, I work every day.", "Yakshanbadan tashqari, har kuni ishlayman.", "Кроме воскресенья, я работаю каждый день."],
  "certain": ["I am certain that I locked the door.", "Eshikni qulflaganimga aminman.", "Я уверен, что запер дверь."],
  "occasionally": ["We occasionally meet for coffee.", "Biz ba'zan qahva ichgani uchrashamiz.", "Изредка мы встречаемся выпить кофе."],
  "do the hoovering": ["I do the hoovering every Saturday.", "Har shanba pilesos qilaman.", "Каждую субботу я пылесошу."],
  "do somebody a favour": ["Could you do me a favour and open the window?", "Menga yordam berib, derazani ocha olasizmi?", "Не сделаешь одолжение — откроешь окно?"],
  "do one's best": ["I will do my best to finish on time.", "O'z vaqtida tugatish uchun qo'limdan kelganini qilaman.", "Я сделаю всё возможное, чтобы закончить вовремя."],
  "make friends": ["He makes friends very easily.", "U juda oson do'st orttiradi.", "Он очень легко заводит друзей."],
  "make an appointment": ["I made an appointment with the doctor.", "Shifokor bilan uchrashuv tayinladim.", "Я записался на приём к врачу."],
  "take ages": ["It takes ages to get there by bus.", "U yerga avtobusda borish juda ko'p vaqt oladi.", "Добираться туда на автобусе — целая вечность."],
  "carry": ["Let me carry that heavy bag for you.", "O'sha og'ir sumkani men ko'tarib beray.", "Давай я понесу эту тяжёлую сумку."],
  "takeaway": ["Let's order a takeaway tonight.", "Bugun kechqurun uyga ovqat buyurtma qilaylik.", "Давай сегодня закажем еду на вынос."],
  "have a rest": ["You look tired, have a rest.", "Charchagan ko'rinasiz, dam oling.", "Ты выглядишь уставшим, отдохни."],
  "have a conversation": ["We had a long conversation about his plans.", "Uning rejalari haqida uzoq suhbatlashdik.", "Мы долго беседовали о его планах."],
  "take medicine": ["Take this medicine twice a day.", "Bu dorini kuniga ikki marta iching.", "Принимайте это лекарство дважды в день."],
  "have a lot of arguments": ["They have a lot of arguments about money.", "Ular pul ustida ko'p bahslashadi.", "Они часто спорят из-за денег."],

  /* ═══════════ 03.09.2026 · 9 F ═══════════ */
  "in the middle of nowhere": ["Their farm is in the middle of nowhere.", "Ularning fermasi juda olis joyda.", "Их ферма находится у чёрта на куличках."],
  "clear": ["The water in the lake was completely clear.", "Ko'ldagi suv butunlay tiniq edi.", "Вода в озере была совершенно прозрачной."],
  "peaceful": ["The village is quiet and peaceful.", "Qishloq tinch va osoyishta.", "Деревня тихая и спокойная."],
  "remote": ["They live in a remote mountain village.", "Ular olis tog' qishlog'ida yashaydi.", "Они живут в отдалённой горной деревне."],
  "sunny": ["It was a bright and sunny morning.", "Yorqin va quyoshli tong edi.", "Было яркое и солнечное утро."],
  "reach": ["We reached the hotel after midnight.", "Mehmonxonaga yarim tundan keyin yetib bordik.", "Мы добрались до отеля после полуночи."],
  "journey": ["The journey to the island takes six hours.", "Orolga sayohat olti soat davom etadi.", "Дорога до острова занимает шесть часов."],
  "supply": ["The village has a good supply of clean water.", "Qishloqda toza suv ta'minoti yaxshi.", "В деревне хорошее снабжение чистой водой."],
  "decade": ["The city has grown a lot in the last decade.", "So'nggi o'n yillikda shahar ancha o'sdi.", "За последнее десятилетие город сильно вырос."],
  "basic": ["He only knows a few basic words in French.", "U fransuz tilida faqat bir nechta asosiy so'zni biladi.", "Он знает лишь несколько основных слов по-французски."],
  "daily routine": ["Exercise is part of my daily routine.", "Mashq — kunlik tartibimning bir qismi.", "Зарядка — часть моего распорядка дня."],
  "entertainment": ["There is not much entertainment in this town.", "Bu shaharda ko'ngil ochish uchun joy kam.", "В этом городке мало развлечений."],
  "wreck": ["Divers found the wreck of an old ship.", "G'avvoslar eski kemaning qoldig'ini topishdi.", "Водолазы нашли обломки старого корабля."],
  "run out of": ["We have run out of milk again.", "Sutimiz yana tugab qoldi.", "У нас снова закончилось молоко."],
  "fuel": ["The plane needed more fuel for the trip.", "Samolyotga safar uchun ko'proq yoqilg'i kerak edi.", "Самолёту нужно было больше топлива для рейса."],
  "remoteness": ["The remoteness of the island makes life hard.", "Orolning uzoqligi hayotni qiyinlashtiradi.", "Отдалённость острова усложняет жизнь."],
  "paradise": ["For me, this beach is paradise.", "Men uchun bu sohil — jannat.", "Для меня этот пляж — рай."],
  "drop": ["The temperature dropped to zero at night.", "Kechasi harorat nolgacha tushdi.", "Ночью температура упала до нуля."],
  "crime": ["Crime is very low in this area.", "Bu hududda jinoyatchilik juda past.", "В этом районе очень низкая преступность."],

  /* ═══════════ 05.09.2026 · 9 G / 9 H ═══════════ */
  "comparison": ["The comparison between the two cities is interesting.", "Ikki shahar o'rtasidagi taqqoslash qiziqarli.", "Сравнение двух городов интересно."],
  "above": ["There is a lamp above the table.", "Stol ustida chiroq bor.", "Над столом висит лампа."],
  "bright": ["The kitchen is bright and modern.", "Oshxona yorqin va zamonaviy.", "Кухня светлая и современная."],
  "cosy": ["Their living room is small but cosy.", "Ularning mehmonxonasi kichik, lekin shinam.", "Их гостиная маленькая, но уютная."],
  "uncomfortable": ["These shoes are really uncomfortable.", "Bu poyabzal juda noqulay.", "Эта обувь очень неудобная."],
  "obvious": ["It was obvious that he was tired.", "Uning charchaganligi aniq edi.", "Было очевидно, что он устал."],
  "similarity": ["There is a clear similarity between the two photos.", "Ikki surat o'rtasida aniq o'xshashlik bor.", "Между двумя фотографиями есть явное сходство."],
  "difference": ["What is the difference between these two words?", "Bu ikki so'z orasida qanday farq bor?", "В чём разница между этими двумя словами?"],
  "speculate": ["We can only speculate about the reason.", "Sabab haqida faqat taxmin qilishimiz mumkin.", "Мы можем только предполагать о причине."],
  "whereas": ["My brother is very quiet, whereas I talk a lot.", "Akam juda tinch, holbuki men ko'p gapiraman.", "Мой брат очень тихий, тогда как я много говорю."],
  "both": ["Both of my sisters live in Tashkent.", "Ikkala opam ham Toshkentda yashaydi.", "Обе мои сестры живут в Ташкенте."],
  "as if": ["He looked at me as if he knew me.", "U menga go'yoki tanish odamdek qaradi.", "Он посмотрел на меня так, как будто знал меня."],
  "perhaps": ["Perhaps we should call him first.", "Balki avval unga qo'ng'iroq qilishimiz kerak.", "Возможно, нам стоит сначала ему позвонить."],
  "foreign": ["He speaks three foreign languages.", "U uchta xorijiy tilda gapiradi.", "Он говорит на трёх иностранных языках."],
  "fairly": ["The test was fairly easy for me.", "Test men uchun ancha oson bo'ldi.", "Тест оказался для меня довольно лёгким."],
  "although": ["Although it was raining, we went for a walk.", "Yomg'ir yog'ayotganiga qaramasdan, biz sayr qildik.", "Хотя шёл дождь, мы пошли гулять."],
  "contrast": ["The author contrasts life in the city and in the village.", "Muallif shahar va qishloq hayotini qiyoslaydi.", "Автор противопоставляет жизнь в городе и в деревне."],

  /* ═══════════ NOTO'G'RI FE'LLAR ═══════════ */
  "cost": ["The tickets cost forty dollars each.", "Chiptalar har biri qirq dollar turadi.", "Билеты стоят по сорок долларов."],
  "cut": ["He cut the bread into six pieces.", "U nonni olti bo'lakka kesdi.", "Он разрезал хлеб на шесть кусков."],
  "hit": ["The ball hit the window but did not break it.", "To'p derazaga urildi, lekin sindirmadi.", "Мяч ударился в окно, но не разбил его."],
  "hurt": ["My back hurts after the long drive.", "Uzoq yo'ldan keyin belim og'riyapti.", "После долгой поездки у меня болит спина."],
  "let": ["My parents let me stay out until ten.", "Ota-onam menga soat o'ngacha tashqarida qolishga ruxsat berdi.", "Родители разрешили мне гулять до десяти."],
  "put": ["Put the milk in the fridge, please.", "Iltimos, sutni muzlatgichga qo'ying.", "Поставь молоко в холодильник, пожалуйста."],
  "shut": ["Please shut the door quietly.", "Iltimos, eshikni sekin yoping.", "Пожалуйста, закройте дверь тихо."],
  "send": ["I sent him a message an hour ago.", "Unga bir soat oldin xabar yubordim.", "Я отправил ему сообщение час назад."],
  "spend": ["We spent two weeks in Turkey.", "Biz Turkiyada ikki hafta o'tkazdik.", "Мы провели две недели в Турции."],
  "build": ["They built this bridge in 1998.", "Bu ko'prikni 1998-yilda qurishgan.", "Этот мост построили в 1998 году."],
  "burn": ["I burnt the rice again.", "Guruchni yana kuydirib qo'ydim.", "Я снова сжёг рис."],
  "learn": ["She learnt Spanish in six months.", "U ispan tilini olti oyda o'rgandi.", "Она выучила испанский за шесть месяцев."],
  "smell": ["This soup smells delicious.", "Bu sho'rvaning hidi mazali.", "Этот суп вкусно пахнет."],
  "feel": ["I feel much better today.", "Bugun o'zimni ancha yaxshi his qilyapman.", "Сегодня я чувствую себя гораздо лучше."],
  "leave": ["The train leaves at ten past seven.", "Poyezd yetti-u o'nda jo'naydi.", "Поезд отправляется в десять минут восьмого."],
  "meet": ["We met at the university ten years ago.", "Biz o'n yil oldin universitetda uchrashganmiz.", "Мы познакомились в университете десять лет назад."],
  "mean": ["What does this word mean?", "Bu so'z nimani anglatadi?", "Что означает это слово?"],
  "shoot": ["The hunter shot at the bird and missed.", "Ovchi qushga o'q uzdi va tegizolmadi.", "Охотник выстрелил в птицу и промахнулся."],
  "get": ["I got a letter from my brother yesterday.", "Kecha akamdan xat oldim.", "Вчера я получил письмо от брата."],
  "light": ["She lit a candle and sat down.", "U shamni yoqdi va o'tirdi.", "Она зажгла свечу и села."],
  "sit": ["Please sit down and wait a moment.", "Iltimos, o'tiring va bir oz kuting.", "Пожалуйста, садитесь и подождите минуту."],
  "sleep": ["I slept only four hours last night.", "Kecha atigi to'rt soat uxladim.", "Прошлой ночью я спал всего четыре часа."],
  "bring": ["Bring your passport to the meeting.", "Uchrashuvga pasportingizni olib keling.", "Принесите паспорт на встречу."],
  "buy": ["I bought this jacket last winter.", "Bu kurtkani o'tgan qish sotib oldim.", "Я купил эту куртку прошлой зимой."],
  "fight": ["The two boys fought over a toy.", "Ikki bola o'yinchoq ustida urishdi.", "Двое мальчиков подрались из-за игрушки."],
  "think": ["I think you are right.", "Menimcha, siz haqsiz.", "Думаю, ты прав."],
  "catch": ["He caught the ball with one hand.", "U to'pni bir qo'llab ushlab qoldi.", "Он поймал мяч одной рукой."],
  "teach": ["She teaches English at a private school.", "U xususiy maktabda ingliz tili o'qitadi.", "Она преподаёт английский в частной школе."],
  "sell": ["They sold their old car last month.", "Ular o'tgan oy eski mashinasini sotishdi.", "В прошлом месяце они продали свою старую машину."],
  "tell": ["Tell me the truth, please.", "Iltimos, menga haqiqatni ayting.", "Пожалуйста, скажи мне правду."],
  "find": ["I found my keys under the sofa.", "Kalitlarimni divan tagidan topdim.", "Я нашёл ключи под диваном."],
  "have": ["They have two children and a dog.", "Ularning ikkita bolasi va iti bor.", "У них двое детей и собака."],
  "hear": ["Did you hear that strange noise?", "O'sha g'alati ovozni eshitdingizmi?", "Ты слышал этот странный звук?"],
  "hold": ["Hold my bag for a second, please.", "Iltimos, sumkamni bir soniya ushlab turing.", "Подержи мою сумку секунду, пожалуйста."],
  "read": ["I read two books during the holiday.", "Ta'til davomida ikkita kitob o'qidim.", "За отпуск я прочитал две книги."],
  "say": ["He said nothing and left the room.", "U hech narsa demay xonadan chiqdi.", "Он ничего не сказал и вышел из комнаты."],
  "pay": ["I paid for the tickets by card.", "Chiptalarni karta bilan to'ladim.", "Я оплатил билеты картой."],
  "make": ["She made a cake for his birthday.", "U tug'ilgan kuniga tort tayyorladi.", "Она испекла торт на его день рождения."],
  "stand": ["A tall tree stands in front of the house.", "Uy oldida baland daraxt turibdi.", "Перед домом стоит высокое дерево."],
  "understand": ["I did not understand the last question.", "Oxirgi savolni tushunmadim.", "Я не понял последний вопрос."],
  "break": ["He broke his phone on the first day.", "U telefonini birinchi kuniyoq sindirdi.", "Он разбил телефон в первый же день."],
  "choose": ["It was hard to choose between the two.", "Ikkalasidan birini tanlash qiyin bo'ldi.", "Было трудно выбрать между этими двумя."],
  "speak": ["Could you speak more slowly, please?", "Iltimos, sekinroq gapira olasizmi?", "Не могли бы вы говорить помедленнее?"],
  "steal": ["Someone stole his bicycle last night.", "Kecha kimdir uning velosipedini o'g'irlab ketdi.", "Прошлой ночью кто-то украл его велосипед."],
  "wake": ["I woke up at five this morning.", "Bugun ertalab beshda uyg'ondim.", "Сегодня утром я проснулся в пять."],
  "drive": ["She drives to work every day.", "U har kuni ishga mashinada boradi.", "Она каждый день ездит на работу на машине."],
  "ride": ["He rode a horse for the first time.", "U birinchi marta otga mindi.", "Он впервые прокатился на лошади."],
  "rise": ["Prices have risen again this year.", "Bu yil narxlar yana ko'tarildi.", "В этом году цены снова выросли."],
  "write": ["He wrote three letters yesterday evening.", "U kecha kechqurun uchta xat yozdi.", "Вчера вечером он написал три письма."],
  "bite": ["The dog bit him on the leg.", "It uning oyog'ini tishladi.", "Собака укусила его за ногу."],
  "hide": ["The boy hid behind the door.", "Bola eshik orqasiga yashirindi.", "Мальчик спрятался за дверью."],
  "eat": ["We ate dinner at eight o'clock.", "Kechki ovqatni soat sakkizda yedik.", "Мы поужинали в восемь часов."],
  "fall": ["He fell on the ice and broke his arm.", "U muzda yiqilib, qo'lini sindirdi.", "Он упал на льду и сломал руку."],
  "forget": ["I forgot to call her back.", "Unga qayta qo'ng'iroq qilishni unutdim.", "Я забыл ей перезвонить."],
  "give": ["She gave me a book for my birthday.", "U tug'ilgan kunimga menga kitob berdi.", "Она подарила мне книгу на день рождения."],
  "see": ["I saw him at the station this morning.", "Bugun ertalab uni bekatda ko'rdim.", "Сегодня утром я видел его на вокзале."],
  "take": ["Take an umbrella, it may rain.", "Soyabon oling, yomg'ir yog'ishi mumkin.", "Возьми зонт, может пойти дождь."],
  "blow": ["A cold wind was blowing all night.", "Tun bo'yi sovuq shamol esdi.", "Всю ночь дул холодный ветер."],
  "grow": ["These flowers grow very quickly.", "Bu gullar juda tez o'sadi.", "Эти цветы растут очень быстро."],
  "know": ["I have known him since childhood.", "Men uni bolalikdan bilaman.", "Я знаю его с детства."],
  "throw": ["Do not throw the ball in the house.", "Uy ichida to'p tashlamang.", "Не бросай мяч в доме."],
  "fly": ["We flew to Istanbul last summer.", "O'tgan yozda Istanbulga uchdik.", "Прошлым летом мы летали в Стамбул."],
  "draw": ["My daughter draws very well.", "Qizim juda yaxshi rasm chizadi.", "Моя дочь очень хорошо рисует."],
  "show": ["Show me the photos from your trip.", "Sayohatingizdan olingan suratlarni ko'rsating.", "Покажи мне фотографии из поездки."],
  "begin": ["The film begins at half past eight.", "Film sakkiz yarimda boshlanadi.", "Фильм начинается в половине девятого."],
  "drink": ["She never drinks coffee after six o'clock.", "U hech qachon soat oltidan keyin qahva ichmaydi.", "Она никогда не пьёт кофе после шести."],
  "swim": ["He swims in the river every summer.", "U har yozda daryoda suzadi.", "Каждое лето он плавает в реке."],
  "ring": ["The phone rang three times and stopped.", "Telefon uch marta jiringladi va to'xtadi.", "Телефон прозвонил три раза и замолчал."],
  "sing": ["The children sang a beautiful song.", "Bolalar chiroyli qo'shiq kuylashdi.", "Дети спели красивую песню."],
  "run": ["I run five kilometres every morning.", "Har kuni ertalab besh kilometr yuguraman.", "Каждое утро я пробегаю пять километров."],
  "come": ["Come to my place at seven.", "Soat yettida uyimga keling.", "Приходи ко мне в семь."],
  "become": ["He became a doctor at the age of thirty.", "U o'ttiz yoshida shifokor bo'ldi.", "Он стал врачом в тридцать лет."],
  "be": ["I was at home all day yesterday.", "Kecha kun bo'yi uyda edim.", "Вчера я весь день был дома."],
  "do": ["What do you do at the weekend?", "Dam olish kunlari nima qilasiz?", "Чем ты занимаешься по выходным?"],
  "go": ["I go to the gym three times a week.", "Men haftada uch marta sport zaliga boraman.", "Я хожу в спортзал три раза в неделю."],
  "shine": ["The sun shone brightly all afternoon.", "Quyosh tushdan keyin yorqin charaqladi.", "Солнце ярко светило весь день."],
  "wear": ["She wore a blue dress to the party.", "U bazmga ko'k libos kiydi.", "Она надела на вечеринку синее платье."],
  "win": ["Our team won the cup last year.", "Jamoamiz o'tgan yili kubokni yutdi.", "В прошлом году наша команда выиграла кубок."]

};
