/* ============================================================
   myvocab — Vocabulary Dataset
   Contains all 311 vocabulary items across lessons & dates.
   Format: [en_BR, en_US(or null), ipaBR, latBR, cyrBR, ipaUS, latUS, cyrUS, RU, UZ]
   ============================================================ */
const GROUPS = [
 {date:"2026-08-18", topic:"8 A / 8 B", w:[
  ["Active",null,"/ˈæktɪv/","ektiv","эктив","/ˈæktɪv/","ektiv","эктив","Активный","Faol"],
  ["How often",null,"/ˌhaʊ ˈɒfn/","hau ofn","хау офн","/ˌhaʊ ˈɔːfn/","hau oofn","хау оофн","Как часто","Qancha vaqtda, qanchalik tez-tez"],
  ["Normally",null,"/ˈnɔːməli/","noomali","ноомали","/ˈnɔːrməli/","noormali","ноормали","Обычно","Odatda"],
  ["Team",null,"/tiːm/","tiim","тиим","/tiːm/","tiim","тиим","Команда","Jamoa"],
  ["Activity",null,"/ækˈtɪvəti/","ektivati","эктивати","/ækˈtɪvəti/","ektivadi","эктивади","Деятельность, занятие","Mashg‘ulot, faoliyat"],
  ["Combat",null,"/ˈkɒmbæt/","kombet","комбэт","/ˈkɑːmbæt/","kaambet","каамбэт","Бой, сражение; сражаться","Jang; jang qilmoq"],
  ["Correct",null,"/kəˈrekt/","karekt","карэкт","/kəˈrekt/","karekt","карэкт","Правильный","To‘g‘ri"],
  ["Add",null,"/æd/","ed","эд","/æd/","ed","эд","Прибавлять, добавлять","Qo‘shmoq"],
  ["Fall over",null,"/ˌfɔːl ˈəʊvə(r)/","fool ouva","фоол оува","/ˌfɔːl ˈoʊvɚ/","fool ouvar","фоол оувар","Упасть, свалиться","Yiqilib tushmoq"],
  ["Injure",null,"/ˈɪndʒə(r)/","inja","инжа","/ˈɪndʒɚ/","injar","инжар","Ранить, травмировать","Shikastlamoq, jarohatlamoq"],
  ["Score",null,"/skɔː(r)/","skoo","скоо","/skɔːr/","skor","скор","Забить гол, забить мяч в ворота","Go‘l urmoq"],
  ["Break a record",null,"/ˌbreɪk ə ˈrekɔːd/","breyk a rekood","брэйк а рэкоод","/ˌbreɪk ə ˈrekɚd/","breyk a rekard","брэйк а рэкард","Побить рекорд","Rekord o‘rnatmoq"],
  ["Take part",null,"/ˌteɪk ˈpɑːt/","teyk paat","тэйк паат","/ˌteɪk ˈpɑːrt/","teyk paart","тэйк паарт","Участвовать","Qatnashmoq, ishtirok etmoq"],
  ["Experience",null,"/ɪkˈspɪəriəns/","ikspiarians","икспиарианс","/ɪkˈspɪriəns/","ikspirians","икспирианс","Опыт","Tajriba"],
  ["Competition",null,"/ˌkɒmpəˈtɪʃn/","kompatishn","компатишн","/ˌkɑːmpəˈtɪʃn/","kaampatishn","каампатишн","Соревнование","Musobaqa"],
  ["Support",null,"/səˈpɔːt/","sapoot","сапоот","/səˈpɔːrt/","sapoort","сапоорт","Поддерживать","Qo‘llab-quvvatlamoq"],
  ["Supporter",null,"/səˈpɔːtə(r)/","sapoota","сапоота","/səˈpɔːrtɚ/","sapoordar","сапоордар","Сторонник, болельщик","Tarafdor, muxlis"]
 ]},
 {date:"2026-08-15", topic:"7 G", w:[
  ["Price",null,"/praɪs/","prays","прайс","/praɪs/","prays","прайс","Цена","Narx"],
  ["Look for",null,"/ˈlʊk fə(r)/","luk fo","лук фо","/ˈlʊk fɚ/","luk far","лук фар","Искать","Qidirmoq"],
  ["Popular",null,"/ˈpɒpjələ(r)/","popyula","попьюла","/ˈpɑːpjəlɚ/","paapyular","паапьюлар","Популярный","Mashhur"],
  ["A bit",null,"/ə ˈbɪt/","a bit","а бит","/ə ˈbɪt/","a bit","а бит","Немного","Ozgina, bir oz"],
  ["Debit card",null,"/ˈdebɪt kɑːd/","debit kaad","дэбит каад","/ˈdebɪt kɑːrd/","debit kaard","дэбит каард","Дебетовая карта","Debit kartasi"],
  ["Correctly",null,"/kəˈrektli/","karektli","карэктли","/kəˈrektli/","karektli","карэктли","Правильно, верно","To‘g‘ri"],
  ["Feature",null,"/ˈfiːtʃə(r)/","fiicha","фиича","/ˈfiːtʃɚ/","fiichar","фиичар","Особенность, функция","Xususiyat"],
  ["Battery life",null,"/ˈbætri laɪf/","betri layf","бэтри лайф","/ˈbætəri laɪf/","bedari layf","бэдари лайф","Срок службы батареи","Batareyaning ishlash muddati"],
  ["Built-in 4G",null,"/ˌbɪlt ɪn ˌfɔː ˈdʒiː/","bilt in foo jii","билт ин фоо жии","/ˌbɪlt ɪn ˌfɔːr ˈdʒiː/","bilt in foor jii","билт ин фоор жии","Встроенный 4G","4G o‘rnatilgan"],
  ["Built-in webcam",null,"/ˌbɪlt ɪn ˈwebkæm/","bilt in vebkem","билт ин вэбкэм","/ˌbɪlt ɪn ˈwebkæm/","bilt in vebkem","билт ин вэбкэм","Встроенная веб-камера","Veb-kamera o‘rnatilgan"],
  ["Case",null,"/keɪs/","keys","кэйс","/keɪs/","keys","кэйс","Чехол (телефона)","G‘ilof, chexol"],
  ["Memory card slot",null,"/ˈmeməri kɑːd slɒt/","memari kaad slot","мэмари каад слот","/ˈmeməri kɑːrd slɑːt/","memari kaard slaat","мэмари каард слаат","Слот для карты памяти","Xotira karta uyasi"],
  ["Motion sensor",null,"/ˈməʊʃn ˈsensə(r)/","moushn sensa","моушн сэнса","/ˈmoʊʃn ˈsensɚ/","moushn sensar","моушн сэнсар","Датчик движения","Harakat sensori"],
  ["Touchscreen",null,"/ˈtʌtʃskriːn/","tachskriin","тачскриин","/ˈtʌtʃskriːn/","tachskriin","тачскриин","Сенсорный экран","Sensorli ekran"],
  ["Wireless",null,"/ˈwaɪələs/","vayalas","вайалас","/ˈwaɪɚləs/","vayarlas","вайарлас","Беспроводной","Simsiz"],
  ["Wireless speakers",null,"/ˈwaɪələs ˈspiːkəz/","vayalas spiikaz","вайалас спииказ","/ˈwaɪɚləs ˈspiːkɚz/","vayarlas spiikarz","вайарлас спиикарз","Беспроводные колонки","Simsiz kolonka"],
  ["Cash",null,"/kæʃ/","kesh","кэш","/kæʃ/","kesh","кэш","Наличные деньги","Naqd pul"],
  ["Change",null,"/tʃeɪndʒ/","cheynj","чэйнж","/tʃeɪndʒ/","cheynj","чэйнж","Менять; сдача","Almashtirmoq; qaytim"],
  ["Receipt",null,"/rɪˈsiːt/","risiit","рисиит","/rɪˈsiːt/","risiit","рисиит","Квитанция, чек","Kvitansiya, chek"],
  ["Suggest",null,"/səˈdʒest/","sajest","сажэст","/səɡˈdʒest/","sagjest","сагжэст","Предлагать","Taklif qilmoq"],
  ["Confirm",null,"/kənˈfɜːm/","kanfyom","канфём","/kənˈfɝːm/","kanfyorm","канфёрм","Подтверждать","Tasdiqlamoq"],
  ["Currency",null,"/ˈkʌrənsi/","karansi","каранси","/ˈkɜːrənsi/","kyoransi","кёранси","Валюта","Valyuta"],
  ["Payment method",null,"/ˈpeɪmənt ˈmeθəd/","peymant methad","пэймант мэсад","/ˈpeɪmənt ˈmeθəd/","peymant methad","пэймант мэсад","Способ оплаты","To‘lov usuli"]
 ]},
 {date:"2026-08-15", topic:"7 H", w:[
  ["Narrative",null,"/ˈnærətɪv/","nerativ","нэратив","/ˈnerətɪv/","neradiv","нэрадив","Рассказ, повествование","Hikoya"],
  ["Locked",null,"/lɒkt/","lokt","локт","/lɑːkt/","laakt","лаакт","Заблокирован","Qulflangan"],
  ["Electronic device",null,"/ɪˌlekˈtrɒnɪk dɪˈvaɪs/","ilektronik divays","илэктроник дивайс","/ɪˌlekˈtrɑːnɪk dɪˈvaɪs/","ilektraanik divays","илэктраник дивайс","Электронное устройство, гаджет","Elektron qurilma"],
  ["Cause",null,"/kɔːz/","kooz","кооз","/kɑːz/","kaaz","кааз","Причинять, вызывать","Sabab bo‘lmoq"],
  ["Afterwards",null,"/ˈɑːftəwədz/","aaftavadz","аафтавадз","/ˈæftɚwɚdz/","eftarvardz","эфтарвардз","Впоследствии, потом","Keyin, so‘ngra"],
  ["Accept",null,"/əkˈsept/","aksept","аксэпт","/əkˈsept/","aksept","аксэпт","Принимать","Qabul qilmoq"],
  ["Error",null,"/ˈerə(r)/","era","эра","/ˈerɚ/","erar","эрар","Ошибка","Xato"],
  ["Unfortunately",null,"/ʌnˈfɔːtʃənətli/","anfoochanatli","анфоочанатли","/ʌnˈfɔːrtʃənətli/","anfoorchanatli","анфоорчанатли","К сожалению","Afsuski"],
  ["Amazingly",null,"/əˈmeɪzɪŋli/","ameyzingli","амэйзингли","/əˈmeɪzɪŋli/","ameyzingli","амэйзингли","Удивительно","Hayratlanarli"],
  ["Type",null,"/taɪp/","tayp","тайп","/taɪp/","tayp","тайп","Тип, вид","Turi, xili"],
  ["Swap",null,"/swɒp/","svop","своп","/swɑːp/","svaap","сваап","Менять, обменивать","Almashtirmoq"],
  ["By accident",null,"/baɪ ˈæksɪdənt/","bay eksidant","бай эксидант","/baɪ ˈæksɪdənt/","bay eksidant","бай эксидант","Случайно","Tasodifan"],
  ["Lend",null,"/lend/","lend","лэнд","/lend/","lend","лэнд","Одалживать, давать в долг","Qarz bermoq"],
  ["Safely",null,"/ˈseɪfli/","seyfli","сэйфли","/ˈseɪfli/","seyfli","сэйфли","Безопасно","Xavfsiz"],
  ["In the end",null,"/ɪn ðə ˈend/","in dhe end","ин зэ энд","/ɪn ðə ˈend/","in dhe end","ин зэ энд","В конце концов","So‘ngida, oxir-oqibat"],
  ["Set the scene",null,"/ˌset ðə ˈsiːn/","set dhe siin","сэт зэ сиин","/ˌset ðə ˈsiːn/","sed dhe siin","сэд зэ сиин","Задать обстановку, описать место","Sahnalashtirmoq"],
  ["Recently",null,"/ˈriːsntli/","riisntli","рииснтли","/ˈriːsntli/","riisntli","рииснтли","Недавно","Yaqinda"],
  ["Later",null,"/ˈleɪtə(r)/","leyta","лэйта","/ˈleɪtɚ/","leydar","лэйдар","Позже","Keyinroq"],
  ["Comma",null,"/ˈkɒmə/","koma","кома","/ˈkɑːmə/","kaama","каама","Запятая","Vergul"],
  ["Quotation mark",null,"/kwəʊˈteɪʃn mɑːk/","kvouteyshn maak","квоутэйшн маак","/kwoʊˈteɪʃn mɑːrk/","kvouteyshn maark","квоутэйшн маарк","Кавычки","Qo‘shtirnoq"],
  ["Question mark",null,"/ˈkwestʃən mɑːk/","kveschan maak","квэсчан маак","/ˈkwestʃən mɑːrk/","kveschan maark","квэсчан маарк","Вопросительный знак","So‘roq belgisi"],
  ["Exclamation mark",null,"/ˌekskləˈmeɪʃn mɑːk/","eksklameyshn maak","эксклaмэйшн маак","/ˌekskləˈmeɪʃn mɑːrk/","eksklameyshn maark","эксклaмэйшн маарк","Восклицательный знак","Undov belgisi"],
  ["Particular",null,"/pəˈtɪkjələ(r)/","patikyula","патикьюла","/pɚˈtɪkjəlɚ/","partikyular","партикьюлар","Особенный, конкретный","Maxsus, alohida"],
  ["Event",null,"/ɪˈvent/","ivent","ивэнт","/ɪˈvent/","ivent","ивэнт","Событие","Hodisa, voqea"]
 ]},
 {date:"2026-08-13", topic:"7 E", w:[
  ["Put on",null,"/ˌpʊt ˈɒn/","put on","пут он","/ˌpʊt ˈɑːn/","pud aan","пуд аан","Надевать","Kiyib olmoq"],
  ["Back up",null,"/ˌbæk ˈʌp/","bek ap","бэк ап","/ˌbæk ˈʌp/","bek ap","бэк ап","Резервное копирование","Zaxiralamoq"],
  ["Plug in",null,"/ˌplʌɡ ˈɪn/","plag in","плаг ин","/ˌplʌɡ ˈɪn/","plag in","плаг ин","Подключать","Ulamoq"],
  ["Scan in",null,"/ˌskæn ˈɪn/","sken in","скэн ин","/ˌskæn ˈɪn/","sken in","скэн ин","Сканировать","Skaner qilmoq"],
  ["Shut down",null,"/ˌʃʌt ˈdaʊn/","shat daun","шат даун","/ˌʃʌt ˈdaʊn/","shat daun","шат даун","Выключить, закрыть (компьютер)","O‘chirmoq, yopmoq (kompyuter)"],
  ["Turn off",null,"/ˌtɜːn ˈɒf/","tyon of","тён оф","/ˌtɝːn ˈɔːf/","tyorn oof","тёрн ооф","Выключить","O‘chirmoq"],
  ["Turn on",null,"/ˌtɜːn ˈɒn/","tyon on","тён он","/ˌtɝːn ˈɑːn/","tyorn aan","тёрн аан","Включать","Yoqmoq"],
  ["Turn up",null,"/ˌtɜːn ˈʌp/","tyon ap","тён ап","/ˌtɝːn ˈʌp/","tyorn ap","тёрн ап","Усиливать звук","Ovozini baland qilmoq"],
  ["Turn down",null,"/ˌtɜːn ˈdaʊn/","tyon daun","тён даун","/ˌtɝːn ˈdaʊn/","tyorn daun","тёрн даун","Убавить громкость","Ovozini pasaytirmoq"],
  ["Type in",null,"/ˌtaɪp ˈɪn/","tayp in","тайп ин","/ˌtaɪp ˈɪn/","tayp in","тайп ин","Впечатать, набрать","Kompyuterda yozmoq"],
  ["Break down",null,"/ˌbreɪk ˈdaʊn/","breyk daun","брэйк даун","/ˌbreɪk ˈdaʊn/","breyk daun","брэйк даун","Сломаться","Buzilib qolmoq"],
  ["Log off",null,"/ˌlɒɡ ˈɒf/","log of","лог оф","/ˌlɔːɡ ˈɔːf/","loog oof","лоог ооф","Выходить из системы","Tizimdan chiqmoq"],
  ["Log on",null,"/ˌlɒɡ ˈɒn/","log on","лог он","/ˌlɔːɡ ˈɑːn/","loog aan","лоог аан","Входить в систему","Tizimga kirmoq"],
  ["Loud",null,"/laʊd/","laud","лауд","/laʊd/","laud","лауд","Громкий","Baland (ovoz)"],
  ["Application",null,"/ˌæplɪˈkeɪʃn/","eplikeyshn","эпликэйшн","/ˌæpləˈkeɪʃən/","eplakeyshn","эплакэйшн","Заявление","Ariza"]
 ]},
 {date:"2026-08-13", topic:"7 F", w:[
  ["Cyberbullying",null,"/ˈsaɪbəbʊliɪŋ/","saybabuliing","сайбабулиинг","/ˈsaɪbɚbʊliɪŋ/","saybarbuliing","сайбарбулиинг","Кибербуллинг, интернет-травля","Kiber zo‘ravonlik"],
  ["Mention",null,"/ˈmenʃn/","menshn","мэншн","/ˈmenʃən/","menshn","мэншн","Упоминать","Eslatib o‘tmoq"],
  ["Fit",null,"/fɪt/","fit","фит","/fɪt/","fit","фит","Подходить, быть впору","Mos kelmoq"],
  ["Raise money",null,"/ˌreɪz ˈmʌni/","reyz mani","рэйз мани","/ˌreɪz ˈmʌni/","reyz mani","рэйз мани","Собирать деньги","Pul yig‘moq"],
  ["Gig",null,"/ɡɪɡ/","gig","гиг","/ɡɪɡ/","gig","гиг","Концерт, выступление","Konsert, chiqish"],
  ["Campaign",null,"/kæmˈpeɪn/","kempeyn","кэмпэйн","/kæmˈpeɪn/","kempeyn","кэмпэйн","Кампания (акция)","Kampaniya, tashviqot"],
  ["Appear",null,"/əˈpɪə(r)/","apia","апиа","/əˈpɪr/","apir","апир","Появляться","Paydo bo‘lmoq"],
  ["Viral",null,"/ˈvaɪrəl/","vayral","вайрал","/ˈvaɪrəl/","vayral","вайрал","Вирусный (быстро распространяющийся)","Viral, tez tarqaladigan"],
  ["Power",null,"/ˈpaʊə(r)/","paua","пауа","/ˈpaʊɚ/","pauar","пауар","Сила, власть","Kuch, qudrat"],
  ["Well-known",null,"/ˌwel ˈnəʊn/","vel noun","вэл ноун","/ˌwel ˈnoʊn/","vel noun","вэл ноун","Известный","Mashhur, taniqli"],
  ["Victim",null,"/ˈvɪktɪm/","viktim","виктим","/ˈvɪktəm/","viktam","виктам","Жертва","Qurbon"],
  ["Huge",null,"/hjuːdʒ/","hyuuj","хьююж","/hjuːdʒ/","hyuuj","хьююж","Огромный","Juda katta, ulkan"],
  ["Fundraising",null,"/ˈfʌndreɪzɪŋ/","fandreyzing","фандрэйзинг","/ˈfʌndreɪzɪŋ/","fandreyzing","фандрэйзинг","Сбор средств","Mablag‘ yig‘ish"],
  ["Anti-bullying",null,"/ˌænti ˈbʊliɪŋ/","enti buliing","энти булиинг","/ˌæntaɪ ˈbʊliɪŋ/","entay buliing","энтай булиинг","Против травли","Zo‘ravonlikka qarshi"],
  ["Charity",null,"/ˈtʃærəti/","cherati","чэрати","/ˈtʃerəti/","cheradi","чэради","Благотворительность","Xayriya"],
  ["Take place",null,"/ˌteɪk ˈpleɪs/","teyk pleys","тэйк плэйс","/ˌteɪk ˈpleɪs/","teyk pleys","тэйк плэйс","Происходить, состояться","Sodir bo‘lmoq, o‘tkazilmoq"],
  ["Kindness",null,"/ˈkaɪndnəs/","kayndnas","кайнднас","/ˈkaɪndnəs/","kayndnas","кайнднас","Доброта","Mehribonlik"],
  ["Half",null,"/hɑːf/","haaf","хааф","/hæf/","hef","хэф","Половина","Yarim"],
  ["Environment",null,"/ɪnˈvaɪrənmənt/","invayranmant","инвайранмант","/ɪnˈvaɪrənmənt/","invayranmant","инвайранмант","Окружающая среда","Atrof-muhit"],
  ["Celebrity",null,"/səˈlebrəti/","salebrati","сэлэбрати","/səˈlebrəti/","salebradi","сэлэбради","Знаменитость","Mashhur shaxs, yulduz"]
 ]},
 {date:"2026-08-11", topic:"7 C / 7 D", w:[
  ["Instruction",null,"/ɪnˈstrʌkʃn/","instrakshn","инстракшн","/ɪnˈstrʌkʃən/","instrakshn","инстракшн","Инструкция","Ko‘rsatma"],
  ["Experience",null,"/ɪkˈspɪəriəns/","ikspiarians","икспиарианс","/ɪkˈspɪriəns/","ikspirians","икспирианс","Опыт; пережить","Tajriba; boshdan kechirmoq"],
  ["Slow",null,"/sləʊ/","slou","слоу","/sloʊ/","slou","слоу","Медленный","Sekin"],
  ["Access",null,"/ˈækses/","ekses","эксэс","/ˈækses/","ekses","эксэс","Иметь доступ к чему-л.","Kirish (kompyuterga)"],
  ["Crash",null,"/kræʃ/","kresh","крэш","/kræʃ/","kresh","крэш","Разбиться, сломаться","Buzilmoq (kompyuter)"],
  ["Lose",null,"/luːz/","luuz","луз","/luːz/","luuz","луз","Терять","Yo‘qotmoq"],
  ["Set up",null,"/ˌset ˈʌp/","set ap","сэт ап","/ˌset ˈʌp/","sed ap","сэд ап","Устанавливать, настроить","Sozlamoq, o‘rnatmoq"],
  ["Remove",null,"/rɪˈmuːv/","rimuuv","римув","/rɪˈmuːv/","rimuuv","римув","Убирать, удалять","Olib tashlamoq"],
  ["Install",null,"/ɪnˈstɔːl/","instool","инстоол","/ɪnˈstɑːl/","instaal","инстаал","Устанавливать","O‘rnatmoq"],
  ["Turn on",null,"/ˌtɜːn ˈɒn/","tyon on","тён он","/ˌtɝːn ˈɑːn/","tyorn aan","тёрн аан","Включать","Yoqmoq"],
  ["Cable",null,"/ˈkeɪbl/","keybl","кэйбл","/ˈkeɪbl/","keybl","кэйбл","Кабель","Kabel"],
  ["Follow",null,"/ˈfɒləʊ/","folou","фолоу","/ˈfɑːloʊ/","faalou","фаалоу","Соблюдать, следовать","Amal qilmoq, ergashmoq"],
  ["Restart",null,"/ˌriːˈstɑːt/","riistaat","риистаат","/ˌriːˈstɑːrt/","riistaart","риистаарт","Перезапускать","Qayta ishga tushirmoq"],
  ["Identify",null,"/aɪˈdentɪfaɪ/","aydentifay","айдэнтифай","/aɪˈdenəfaɪ/","aydenafay","айдэнафай","Определять","Aniqlamoq"],
  ["Sequence",null,"/ˈsiːkwəns/","siikwans","сииквaнс","/ˈsiːkwəns/","siikwans","сииквaнс","Последовательность","Ketma-ketlik"],
  ["Order",null,"/ˈɔːdə(r)/","ooda","оода","/ˈɔːrdɚ/","oordar","оордар","Порядок","Tartib"],
  ["Mark",null,"/mɑːk/","maak","маак","/mɑːrk/","maark","маарк","Отмечать, оценивать","Belgilamoq, baholamoq"],
  ["Stage",null,"/steɪdʒ/","steyj","стэйж","/steɪdʒ/","steyj","стэйж","Этап (сцена)","Bosqich (sahna)"],
  ["Power source",null,"/ˈpaʊə sɔːs/","paua soos","пауа соос","/ˈpaʊɚ sɔːrs/","pauar sors","пауар сорс","Источник питания","Quvvat manbai"],
  ["Miss",null,"/mɪs/","mis","мис","/mɪs/","mis","мис","Пропустить; скучать","O‘tqazib yubormoq; sog‘inmoq"],
  ["Desktop",null,"/ˈdesktɒp/","desktop","дэсктоп","/ˈdesktɑːp/","desktaap","дэсктаап","Рабочий стол (компьютер)","Ish stoli (kompyuter)"],
  ["Drag",null,"/dræɡ/","dreg","дрэг","/dræɡ/","dreg","дрэг","Тащить, перетаскивать","Olib o‘tmoq, sudramoq"],
  ["Folder",null,"/ˈfəʊldə(r)/","foulda","фоулда","/ˈfoʊldɚ/","fouldar","фоулдар","Папка","Papka, jild"],
  ["Solve",null,"/sɒlv/","solv","солв","/sɑːlv/","saalv","саалв","Решать","Hal qilmoq"],
  ["Cause",null,"/kɔːz/","kooz","кооз","/kɑːz/","kaaz","кааз","Причинять, вызывать","Sabab bo‘lmoq"],
  ["Select",null,"/sɪˈlekt/","silekt","силэкт","/sɪˈlekt/","silekt","силэкт","Выбирать","Tanlamoq"],
  ["Update",null,"/ˌʌpˈdeɪt/","apdeyt","апдэйт","/ˈʌpdeɪt/","apdeyt","апдэйт","Обновлять","Yangilamoq"],
  ["Film",null,"/fɪlm/","film","филм","/fɪlm/","film","филм","Снимать кинофильм","Kinoga olmoq"],
  ["Primary school",null,"/ˈpraɪməri skuːl/","praymari skuul","праймари скуул","/ˈpraɪmeri skuːl/","praymeri skuul","праймэри скуул","Начальная школа","Boshlang‘ich maktab"],
  ["Band",null,"/bænd/","bend","бэнд","/bænd/","bend","бэнд","Группа, оркестр","Guruh, orkestr"],
  ["Eat out",null,"/ˌiːt ˈaʊt/","iit aut","иит аут","/ˌiːt ˈaʊt/","iid aut","иид аут","Есть вне дома","Tashqarida ovqatlanmoq"],
  ["Useless",null,"/ˈjuːsləs/","yuuslas","юслас","/ˈjuːsləs/","yuuslas","юслас","Бесполезный","Foydasiz"],
  ["Write down",null,"/ˌraɪt ˈdaʊn/","rayt daun","райт даун","/ˌraɪt ˈdaʊn/","rayd daun","райд даун","Записывать","Yozib qo‘ymoq"]
 ]},
 {date:"2026-08-08", topic:"7 A", w:[
  ["Digital",null,"/ˈdɪdʒɪtl/","dijitl","дижитл","/ˈdɪdʒətl/","dijatl","дижатл","Цифровой","Raqamli"],
  ["Equipment",null,"/ɪˈkwɪpmənt/","ikwipmant","иквипмант","/ɪˈkwɪpmənt/","ikwipmant","иквипмант","Оборудование","Jihoz"],
  ["Modern",null,"/ˈmɒdn/","modn","моди̇н","/ˈmɑːdɚn/","maadarn","маадарн","Современный","Zamonaviy"],
  ["Item",null,"/ˈaɪtəm/","aytam","айтам","/ˈaɪtəm/","aydam","айдам","Вещь, товар","Buyum"],
  ["Charger",null,"/ˈtʃɑːdʒə(r)/","chaaja","чаажа","/ˈtʃɑːrdʒɚ/","chaarjar","чааржар","Зарядка","Zaryadka"],
  ["Headphones",null,"/ˈhedfəʊnz/","hedfounz","хэдфоунз","/ˈhedfoʊnz/","hedfounz","хэдфоунз","Наушники","Quloqchinlar"],
  ["Keyboard",null,"/ˈkiːbɔːd/","kiibood","киибоод","/ˈkiːbɔːrd/","kiibord","кииборд","Клавиатура","Klaviatura"],
  ["Memory stick",null,"/ˈmeməri stɪk/","memari stik","мэмари стик","/ˈmeməri stɪk/","memari stik","мэмари стик","Флешка","Fleshka"],
  ["Router",null,"/ˈruːtə(r)/","ruuta","рута","/ˈraʊtɚ/","raudar","раудар","Роутер","Router (Wi-Fi)"],
  ["Speakers",null,"/ˈspiːkəz/","spiikaz","спииказ","/ˈspiːkɚz/","spiikarz","спиикарз","Колонки","Kolonka"],
  ["Tablet",null,"/ˈtæblət/","teblat","тэблат","/ˈtæblət/","teblat","тэблат","Планшет","Planshet"],
  ["Webcam",null,"/ˈwebkæm/","vebkem","вэбкэм","/ˈwebkæm/","vebkem","вэбкэм","Веб-камера","Veb-kamera"],
  ["Connect to",null,"/kəˈnekt tə/","kanekt tu","канэкт ту","/kəˈnekt tə/","kanekt tu","канэкт ту","Соединять, связывать","Ulanmoq"],
  ["Delete",null,"/dɪˈliːt/","diliit","дилиит","/dɪˈliːt/","diliit","дилиит","Удалять","O‘chirmoq"],
  ["Download",null,"/ˌdaʊnˈləʊd/","daunloud","даунлоуд","/ˈdaʊnloʊd/","daunloud","даунлоуд","Скачивать","Yuklab olmoq"],
  ["Enter",null,"/ˈentə(r)/","enta","энта","/ˈentɚ/","entar","энтар","Вводить, входить","Kiritmoq"],
  ["Offer",null,"/ˈɒfə(r)/","ofa","офа","/ˈɔːfɚ/","oofar","оофар","Предлагать","Taklif qilmoq"],
  ["Scan",null,"/skæn/","sken","скэн","/skæn/","sken","скэн","Сканировать","Skanerlamoq"],
  ["Surf the web",null,"/sɜːf ðə web/","syof dhe veb","сёф зэ вэб","/sɝːf ðə web/","syorf dhe veb","сёрф зэ вэб","Сидеть в интернете","Internetda yurish"]
 ]},
 {date:"2026-08-08", topic:"7 B", w:[
  ["Upload",null,"/ˌʌpˈləʊd/","aploud","аплоуд","/ˈʌploʊd/","aploud","аплоуд","Загружать","Yuklamoq"],
  ["Conversation",null,"/ˌkɒnvəˈseɪʃn/","konvaseyshn","конвасэйшн","/ˌkɑːnvɚˈseɪʃn/","kaanvarseyshn","каанварсэйшн","Разговор","Suhbat"],
  ["Flash drive",null,"/ˈflæʃ draɪv/","flesh drayv","флэш драйв","/ˈflæʃ draɪv/","flesh drayv","флэш драйв","Флешка","Fleshka"],
  ["Speed",null,"/spiːd/","spiid","спиид","/spiːd/","spiid","спиид","Скорость","Tezlik"],
  ["Stand for",null,"/ˈstænd fə(r)/","stend fo","стэнд фо","/ˈstænd fɚ/","stend for","стэнд фор","Обозначать","Anglatmoq"],
  ["Protect",null,"/prəˈtekt/","pratekt","пратэкт","/prəˈtekt/","pratekt","пратэкт","Защищать","Himoya qilmoq"],
  ["Shape",null,"/ʃeɪp/","sheyp","шэйп","/ʃeɪp/","sheyp","шэйп","Форма, вид","Shakl"],
  ["Size",null,"/saɪz/","sayz","сайз","/saɪz/","sayz","сайз","Размер","O‘lcham"],
  ["Get online",null,"/ˌɡet ˈɒnlaɪn/","get onlayn","гэт онлайн","/ˌɡet ˈɑːnlaɪn/","ged aanlayn","гэд аанлайн","Выйти в интернет","Onlayn bo‘lmoq"],
  ["Click",null,"/klɪk/","klik","клик","/klɪk/","klik","клик","Нажимать","Bosmoq"],
  ["Button",null,"/ˈbʌtn/","batn","батн","/ˈbʌtn/","batn","батн","Кнопка","Tugma"],
  ["Press",null,"/pres/","pres","прэс","/pres/","pres","прэс","Нажимать","Bosmoq"],
  ["Return",null,"/rɪˈtɜːn/","rityon","ритён","/rɪˈtɝːn/","rityorn","ритёрн","Возвращение, возвращаться","Orqaga qaytish"],
  ["Annoy",null,"/əˈnɔɪ/","anoy","аной","/əˈnɔɪ/","anoy","аной","Раздражать","Jonga tegmoq"],
  ["Dream",null,"/driːm/","driim","дриим","/driːm/","driim","дриим","Мечта, сон","Orzu, tush"],
  ["Afford",null,"/əˈfɔːd/","afood","афоод","/əˈfɔːrd/","aford","афорд","Иметь возможность","Qurbi yetmoq"],
  ["Fall off",null,"/ˌfɔːl ˈɒf/","fool of","фоол оф","/ˌfɑːl ˈɔːf/","faal oof","фаал ооф","Отваливаться, уменьшаться","Yiqilib tushmoq, kamaymoq"],
  ["Nearly",null,"/ˈnɪəli/","niali","ниали","/ˈnɪrli/","nirli","нирли","Почти, чуть не","Deyarli"],
  ["Give up",null,"/ˌɡɪv ˈʌp/","giv ap","гив ап","/ˌɡɪv ˈʌp/","giv ap","гив ап","Бросать (привычку)","Tashlamoq, to‘xtatish"],
  ["Piece",null,"/piːs/","piis","пиис","/piːs/","piis","пиис","Кусок, часть","Parcha"]
 ]},
 {date:"2026-08-01", topic:"6 C / 6 D", w:[
  ["Miss",null,"/mɪs/","mis","мис","/mɪs/","mis","мис","Пропускать","O‘tqazib yubormoq"],
  ["Grass",null,"/ɡrɑːs/","graas","граас","/ɡræs/","gres","грэс","Трава","O‘t, maysa"],
  ["Paw",null,"/pɔː/","poo","поо","/pɑː/","paa","паа","Лапа","Panja"],
  ["Tent",null,"/tent/","tent","тэнт","/tent/","tent","тэнт","Палатка","Chodir"],
  ["Climb",null,"/klaɪm/","klaym","клайм","/klaɪm/","klaym","клайм","Взбираться, лазить","Tirmashib chiqmoq"],
  ["Feed",null,"/fiːd/","fiid","фиид","/fiːd/","fiid","фиид","Кормить","Ovqatlantirmoq, boqmoq"],
  ["Keep",null,"/kiːp/","kiip","киип","/kiːp/","kiip","киип","Хранить","Saqlamoq"],
  ["Rely",null,"/rɪˈlaɪ/","rilay","рилай","/rɪˈlaɪ/","rilay","рилай","Надеяться, полагаться","Ishonmoq, tayanmoq"],
  ["Safety",null,"/ˈseɪfti/","seyfti","сэйфти","/ˈseɪfti/","seyfti","сэйфти","Безопасность","Xavfsizlik"],
  ["Climber",null,"/ˈklaɪmə(r)/","klayma","клайма","/ˈklaɪmɚ/","klaymar","клаймар","Альпинист","Alpinist"],
  ["Disappear",null,"/ˌdɪsəˈpɪə(r)/","disapia","дисапиа","/ˌdɪsəˈpɪr/","disapir","дисапир","Исчезать","Yo‘qolib ketmoq"],
  ["Identify",null,"/aɪˈdentɪfaɪ/","aydentifay","айдэнтифай","/aɪˈdenəfaɪ/","aydenafay","айдэнафай","Определять","Aniqlamoq"],
  ["Vehicle",null,"/ˈviːəkl/","viiakl","виакл","/ˈviːɪkəl/","viikl","виикл","Транспортное средство","Transport vositasi"],
  ["Camp",null,"/kæmp/","kemp","кэмп","/kæmp/","kemp","кэмп","Лагерь","Oromgoh"],
  ["Solve",null,"/sɒlv/","solv","солв","/sɑːlv/","saalv","саалв","Решать","Hal qilmoq"],
  ["Possession",null,"/pəˈzeʃn/","pazeshn","пазэшн","/pəˈzeʃən/","pazeshn","пазэшн","Владение","Egalik qilish"],
  ["Notice",null,"/ˈnəʊtɪs/","noutis","ноутис","/ˈnoʊtɪs/","noudis","ноудис","Замечать","Bilib qolmoq, sezib qolmoq"],
  ["Path",null,"/pɑːθ/","paath","паас","/pæθ/","peth","пэс","Путь","Yo‘l"],
  ["Put up the tent",null,"/ˌpʊt ʌp ðə ˈtent/","put ap dhe tent","пут ап зэ тэнт","/ˌpʊt ʌp ðə ˈtent/","put ap dhe tent","пут ап зэ тэнт","Ставить палатку","Chodir qurmoq"],
  ["Complain",null,"/kəmˈpleɪn/","kampleyn","камплэйн","/kəmˈpleɪn/","kampleyn","камплэйн","Жаловаться","Shikoyat qilmoq"],
  ["Nightmare",null,"/ˈnaɪtmeə(r)/","naytmea","найтмэа","/ˈnaɪtmer/","naytmer","найтмэр","Страшный сон","Dahshatli tush"],
  ["Count",null,"/kaʊnt/","kaunt","каунт","/kaʊnt/","kaunt","каунт","Считать","Sanamoq"],
  ["Guess",null,"/ɡes/","ges","гэс","/ɡes/","ges","гэс","Предполагать","Taxmin qilmoq"]
 ]},
 {date:"2026-08-06", topic:"6 G", w:[
  ["Relaxing",null,"/rɪˈlæksɪŋ/","rileksing","рилэксинг","/rɪˈlæksɪŋ/","rileksing","рилэксинг","Расслабляющий","Dam oldiradigan"],
  ["Quiet",null,"/ˈkwaɪət/","kwayat","квайат","/ˈkwaɪət/","kwayat","квайат","Тихий","Tinch"],
  ["Warm",null,"/wɔːm/","voom","воом","/wɔːrm/","vorm","ворм","Теплый","Issiq, iliq"],
  ["Beach",null,"/biːtʃ/","biich","биич","/biːtʃ/","biich","биич","Пляж","Sohil bo‘yi"],
  ["Cloud",null,"/klaʊd/","klaud","клауд","/klaʊd/","klaud","клауд","Облако","Bulut"],
  ["Flower",null,"/ˈflaʊə(r)/","flaua","флауа","/ˈflaʊɚ/","flauar","флауар","Цветок","Gul"],
  ["Grass",null,"/ɡrɑːs/","graas","граас","/ɡræs/","gres","грэс","Трава","Maysa"],
  ["Ground",null,"/ɡraʊnd/","graund","граунд","/ɡraʊnd/","graund","граунд","Почва, земля","Yer"],
  ["Moon",null,"/muːn/","muun","мун","/muːn/","muun","мун","Луна","Oy"],
  ["Rock",null,"/rɒk/","rok","рок","/rɑːk/","raak","раак","Скала","Katta tosh"],
  ["Sand",null,"/sænd/","send","сэнд","/sænd/","send","сэнд","Песок","Qum"],
  ["Sea",null,"/siː/","sii","сии","/siː/","sii","сии","Море","Dengiz"],
  ["Sky",null,"/skaɪ/","skay","скай","/skaɪ/","skay","скай","Небо","Osmon"],
  ["Stars",null,"/stɑːz/","staaz","стааз","/stɑːrz/","staarz","стаарз","Звезды","Yulduzlar"],
  ["Sunrise",null,"/ˈsʌnraɪz/","sanrayz","санрайз","/ˈsʌnraɪz/","sanrayz","санрайз","Восход солнца","Quyosh chiqishi"],
  ["Sunset",null,"/ˈsʌnset/","sanset","сансэт","/ˈsʌnset/","sanset","сансэт","Закат","Quyosh botishi"],
  ["Tree",null,"/triː/","trii","трии","/triː/","trii","трии","Дерево","Daraxt"],
  ["Cold",null,"/kəʊld/","kould","коулд","/koʊld/","kould","коулд","Холод, холодный","Sovuq"],
  ["Hot",null,"/hɒt/","hot","хот","/hɑːt/","haat","хаат","Жаркий","Issiq"],
  ["Rainy",null,"/ˈreɪni/","reyni","рэйни","/ˈreɪni/","reyni","рэйни","Дождливый","Yomg‘irli"],
  ["Stormy",null,"/ˈstɔːmi/","stoomi","стооми","/ˈstɔːrmi/","stormi","сторми","Бурный, грозовой","Bo‘ronli"],
  ["Windy",null,"/ˈwɪndi/","vindi","винди","/ˈwɪndi/","vindi","винди","Ветреный","Shamolli"],
  ["Weather",null,"/ˈweðə(r)/","vetha","вэза","/ˈweðɚ/","vethar","вэзар","Погода","Ob-havo"],
  ["In general",null,"/ɪn ˈdʒenrəl/","in jenral","ин жэнрал","/ɪn ˈdʒenrəl/","in jenral","ин жэнрал","В общем","Umuman"],
  ["In the background",null,"/ˈbækɡraʊnd/","in dhe bekgraund","ин зэ бэкграунд","/ˈbækɡraʊnd/","in dhe bekgraund","ин зэ бэкграунд","На заднем фоне","Orqa fonda"],
  ["In the foreground",null,"/ˈfɔːɡraʊnd/","in dhe foograund","ин зэ фоограунд","/ˈfɔːrɡraʊnd/","in dhe forgraund","ин зэ форграунд","На переднем фоне","Oldingi fonda"],
  ["In the distance",null,"/ˈdɪstəns/","in dhe distans","ин зэ дистанс","/ˈdɪstəns/","in dhe distans","ин зэ дистанс","Вдали, вдалеке","Uzoqroqda"],
  ["At the bottom",null,"/ˈbɒtəm/","et dhe botam","эт зэ ботам","/ˈbɑːtəm/","et dhe baadam","эт зэ баадам","На нижней стороне","Pastki tomonda"],
  ["At the top",null,"/tɒp/","et dhe top","эт зэ топ","/tɑːp/","et dhe taap","эт зэ таап","На верхней стороне","Yuqori tomonda"],
  ["Face",null,"/feɪs/","feys","фэйс","/feɪs/","feys","фэйс","Быть обращенным к","Qarab turmoq"],
  ["Look up",null,"/ˌlʊk ˈʌp/","luk ap","лук ап","/ˌlʊk ˈʌp/","luk ap","лук ап","Смотреть наверх","Tepaga qaramoq"],
  ["Look down",null,"/ˌlʊk ˈdaʊn/","luk daun","лук даун","/ˌlʊk ˈdaʊn/","luk daun","лук даун","Смотреть вниз","Pastga qaramoq"],
  ["Climb",null,"/klaɪm/","klaym","клайм","/klaɪm/","klaym","клайм","Взбираться, подниматься","Yuqoriga tirmashib chiqmoq"]
 ]},
 {date:"2026-08-06", topic:"6 H", w:[
  ["Postcard",null,"/ˈpəʊstkɑːd/","poustkaad","поусткаад","/ˈpoʊstkɑːrd/","poustkard","поусткард","Почтовая открытка","Pochta varaqasi"],
  ["Adventure",null,"/ədˈventʃə(r)/","advencha","адвэнча","/ədˈventʃɚ/","advenchar","адвэнчар","Приключение","Sarguzasht"],
  ["Holiday",null,"/ˈhɒlədeɪ/","holidey","холидэй","/ˈhɑːlədeɪ/","haaliday","хаалидэй","Отпуск, день отдыха","Ta’til"],
  ["Activity",null,"/ækˈtɪvəti/","ektivati","эктивати","/ækˈtɪvəti/","ektivadi","эктивади","Занятие, деятельность","Mashg‘ulot"],
  ["Abseil",null,"/ˈæbseɪl/","ebseyl","эбсэйл","/ˈæbseɪl/","ebseyl","эбсэйл","Спускаться на веревке","Arqon bilan pastga tushish"],
  ["Cycle",null,"/ˈsaɪkl/","saykl","сайкл","/ˈsaɪkl/","saykl","сайкл","Ездить на велосипеде","Velosipedda yurmoq"],
  ["Explore",null,"/ɪkˈsplɔː(r)/","iksploo","иксплоо","/ɪkˈsplɔːr/","iksplor","иксплор","Исследовать, изучать","O‘rganib chiqmoq"],
  ["Trek",null,"/trek/","trek","трэк","/trek/","trek","трэк","Поход, переход","Piyoda sayohat qilish"],
  ["Bungee-jump",null,"/ˈbʌndʒi dʒʌmp/","banji jamp","банжи жамп","/ˈbʌndʒi dʒʌmp/","banji jamp","банжи жамп","Прыжки с веревкой","Arqon bilan sakrash"],
  ["Go caving",null,"/ɡəʊ ˈkeɪvɪŋ/","gou keyving","гоу кэйвинг","/ɡoʊ ˈkeɪvɪŋ/","gou keyving","гоу кэйвинг","Пойти в пещеру","G‘orga borish"],
  ["Kite-surfing",null,"/ˈkaɪt sɜːfɪŋ/","kayt syofing","кайт сёфинг","/ˈkaɪt sɝːfɪŋ/","kayt syorfing","кайт сёрфинг","Кайтсёрфинг","Varrak uchurish"],
  ["Watch wildlife",null,"/wɒtʃ ˈwaɪldlaɪf/","voch vayldlayf","воч вайлдлайф","/wɑːtʃ ˈwaɪldlaɪf/","vaach vayldlayf","ваач вайлдлайф","Наблюдать за дикой природой","Yovvoyi tabiatni tomosha qilmoq"],
  ["Windsurf",null,"/ˈwɪndsɜːf/","vindsyof","виндсёф","/ˈwɪndsɝːf/","vindsyorf","виндсёрф","Виндсерфинг","Vindsyorfing"],
  ["Hostel",null,"/ˈhɒstl/","hostl","хостл","/ˈhɑːstl/","haastl","хаастл","Общежитие, хостел","Yotoqxona, kichik mehmonxona"],
  ["Campsite",null,"/ˈkæmpsaɪt/","kempsayt","кэмпсайт","/ˈkæmpsaɪt/","kempsayt","кэмпсайт","Место разбивки лагеря","Lager joyi"],
  ["Cliff",null,"/klɪf/","klif","клиф","/klɪf/","klif","клиф","Скала, утес","Qoya"],
  ["Wish",null,"/wɪʃ/","vish","виш","/wɪʃ/","vish","виш","Желать","Tilamoq, niyat qilmoq"],
  ["Fabulous",null,"/ˈfæbjələs/","febyalas","фэбьялас","/ˈfæbjələs/","febyalas","фэбьялас","Легендарный, потрясающий","Afsonaviy, ajoyib"],
  ["Arrangement",null,"/əˈreɪndʒmənt/","areynjmant","арэйнжмант","/əˈreɪndʒmənt/","areynjmant","арэйнжмант","План, договоренность","Kelishuv, tartib"],
  ["Appropriate",null,"/əˈprəʊpriət/","aproupriat","апроуприат","/əˈproʊpriət/","aproupriat","апроуприат","Соответствующий, подходящий","To‘g‘ri keladigan"]
 ]},
 {date:"2026-08-03", topic:"6 E", w:[
  ["Movement",null,"/ˈmuːvmənt/","muuvment","мувмэнт","/ˈmuːvmənt/","muuvment","мувмэнт","Движение","Harakat"],
  ["Survival",null,"/səˈvaɪvl/","savayvl","сэвайвл","/sɚˈvaɪvəl/","sarvayval","сарвайвал","Выживание","Omon qolish"],
  ["Rainforest",null,"/ˈreɪnfɒrɪst/","reynforist","рэйнфорист","/ˈreɪnˌfɔːrɪst/","reynfoorist","рэйнфоорист","Тропический лес","Tropik o'rmon"],
  ["Camp",null,"/kæmp/","kemp","кэмп","/kæmp/","kemp","кэмп","Лагерь","Oromgoh"],
  ["Shortcut",null,"/ˈʃɔːtkʌt/","shootkat","шооткат","/ˈʃɔːrtkʌt/","shortkat","шорткат","Кратчайший путь","Qisqa yo'l"],
  ["Path",null,"/pɑːθ/","paath","паас","/pæθ/","peth","пэс","Тропинка","Yo'l, so'qmoq"],
  ["Field",null,"/fiːld/","fiild","фиилд","/fiːld/","fiild","фиилд","Поле","Dala"],
  ["Workmate",null,"/ˈwɜːkmeɪt/","vyokmeyt","вёкмэйт","/ˈwɝːkmeɪt/","vyorkmeyt","вёркмэйт","Коллега","Hamkasb"],
  ["Tree trunk",null,"/ˈtriː trʌŋk/","trii trank","трии транк","/ˈtriː trʌŋk/","trii trank","трии транк","Ствол дерева","Daraxt tanasi"],
  ["Crawl",null,"/krɔːl/","krool","кроол","/krɑːl/","kraal","краал","Ползать","Sudralib yurmoq"],
  ["Bush",null,"/bʊʃ/","bush","буш","/bʊʃ/","bush","буш","Куст","Buta"],
  ["Rest",null,"/rest/","rest","рэст","/rest/","rest","рэст","Отдыхать","Dam olmoq"],
  ["Lucky",null,"/ˈlʌki/","laki","лаки","/ˈlʌki/","laki","лаки","Удачный","Omadli"],
  ["Surface",null,"/ˈsɜːfɪs/","syofis","сёфис","/ˈsɝːfɪs/","syorfis","сёрфис","Поверхность","Yuza, sirt"]
 ]},
 {date:"2026-08-03", topic:"6 F", w:[
  ["Strange",null,"/streɪndʒ/","streynj","стрэйнж","/streɪndʒ/","streynj","стрэйнж","Странный","G'alati"],
  ["Fiction",null,"/ˈfɪkʃn/","fikshn","фикшн","/ˈfɪkʃən/","fikshn","фикшн","Выдумка","Uydirma"],
  ["Traveller","Traveler","/ˈtrævələ(r)/","trevala","трэвала","/ˈtrævələr/","trevalar","трэвалар","Путешественник","Sayohatchi"],
  ["Share",null,"/ʃeə(r)/","shea","шэа","/ʃer/","sher","шэр","Разделять","Bo'lishmoq"],
  ["Myth",null,"/mɪθ/","mith","мис","/mɪθ/","mith","мис","Миф","Afsona"],
  ["Case",null,"/keɪs/","keys","кэйс","/keɪs/","keys","кэйс","Случай","Holat"],
  ["Prove",null,"/pruːv/","pruuv","прув","/pruːv/","pruuv","прув","Доказать","Isbotlamoq"],
  ["Giant",null,"/ˈdʒaɪənt/","jayant","жайант","/ˈdʒaɪənt/","jayant","жайант","Гигант","Ulkan"],
  ["Match",null,"/mætʃ/","mech","мэч","/mætʃ/","mech","мэч","Подбирать","Moslashtirmoq"],
  ["Squid",null,"/skwɪd/","skvid","сквид","/skwɪd/","skvid","сквид","Кальмар","Kalmar"],
  ["Ancient",null,"/ˈeɪnʃənt/","eynshant","эйншант","/ˈeɪnʃənt/","eynshant","эйншант","Древний","Qadimiy"],
  ["Realise","Realize","/ˈrɪəlaɪz/","rialayz","риалайз","/ˈriːəlaɪz/","riilayz","риилайз","Осознавать","Tushunib yetmoq"],
  ["Discover",null,"/dɪˈskʌvə(r)/","diskava","дискава","/dɪˈskʌvɚ/","diskavar","дискавар","Обнаруживать","Kashf etmoq"],
  ["Description",null,"/dɪˈskrɪpʃn/","diskripshn","дискрипшн","/dɪˈskrɪpʃən/","diskripshn","дискрипшн","Описание","Tasvir"],
  ["Receive",null,"/rɪˈsiːv/","risiiv","рисиив","/rɪˈsiːv/","risiiv","рисиив","Получать","Qabul qilmoq"],
  ["Inform",null,"/ɪnˈfɔːm/","infoom","инфоом","/ɪnˈfɔːrm/","inform","информ","Сообщать","Xabar bermoq"],
  ["Once",null,"/wʌns/","vans","ванс","/wʌns/","vans","ванс","Однажды","Qachondir, bir marta"],
  ["Appear",null,"/əˈpɪə(r)/","apia","апиа","/əˈpɪr/","apir","апир","Появляться","Paydo bo'lmoq"],
  ["Attack",null,"/əˈtæk/","atek","атэк","/əˈtæk/","atek","атэк","Нападать","Hujum qilmoq"],
  ["Creature",null,"/ˈkriːtʃə(r)/","kriicha","криича","/ˈkriːtʃɚ/","kriichar","криичар","Живое существо","Tirik mavjudot"],
  ["Sailor",null,"/ˈseɪlə(r)/","seyla","сэйла","/ˈseɪlɚ/","seylar","сэйлар","Моряк","Dengizchi"],
  ["Scientist",null,"/ˈsaɪəntɪst/","sayantist","сайантист","/ˈsaɪəntɪst/","sayantist","сайантист","Ученый","Olim"],
  ["Coast",null,"/kəʊst/","koust","коуст","/koʊst/","koust","коуст","Побережье","Dengiz qirg'og'i"],
  ["Fisherman",null,"/ˈfɪʃəmən/","fishaman","фишаман","/ˈfɪʃɚmən/","fisharman","фишарман","Рыбак","Baliqchi"],
  ["Axe",null,"/æks/","eks","экс","/æks/","eks","экс","Топор","Bolta"],
  ["Amazed",null,"/əˈmeɪzd/","ameyzd","амэйзд","/əˈmeɪzd/","ameyzd","амэйзд","Удивленный","Hayratlangan"],
  ["Rarely",null,"/ˈreəli/","reali","рэали","/ˈrerli/","rerli","рэрли","Изредка","Kamdan-kam"],
  ["Exist",null,"/ɪɡˈzɪst/","igzist","игзист","/ɪɡˈzɪst/","igzist","игзист","Существовать","Mavjud bo'lmoq"],
  ["Habitat",null,"/ˈhæbɪtæt/","hebitet","хэбитэт","/ˈhæbɪtæt/","hebidet","хэбидэт","Среда обитания","Yashash muhiti"],
  ["Explorer",null,"/ɪkˈsplɔːrə(r)/","iksploora","иксплоора","/ɪkˈsplɔːrɚ/","iksplorar","иксплорар","Исследователь","Tadqiqotchi"],
  ["Violent",null,"/ˈvaɪələnt/","vayalant","вайалант","/ˈvaɪələnt/","vayalant","вайалант","Жестокий","Shafqatsiz"],
  ["Bad-tempered",null,"/ˌbæd ˈtempəd/","bed-tempad","бэд-тэмпад","/ˌbæd ˈtempɚd/","bed-tempard","бэд-тэмпард","Раздраженный","Badjahl"],
  ["Complete",null,"/kəmˈpliːt/","kampliit","камплиит","/kəmˈpliːt/","kampliit","камплиит","Абсолютный","To'liq"],
  ["Mystery",null,"/ˈmɪstri/","mistri","мистри","/ˈmɪstəri/","mistari","мистари","Тайна","Sir, jumboq"],
  ["Soldier",null,"/ˈsəʊldʒə(r)/","soulja","соулжа","/ˈsoʊldʒɚ/","souljar","соулжар","Солдат","Askar"],
  ["To be familiar with",null,"/fəˈmɪliə wɪð/","familia vith","фамилиа виз","/fəˈmɪljɚ wɪð/","familyar vith","фамильяр виз","Быть знакомым","Tanish bo'lmoq"],
  ["Politician",null,"/ˌpɒləˈtɪʃn/","politishn","политишн","/ˌpɑːləˈtɪʃən/","paalitishn","паалитишн","Политик","Siyosatchi"],
  ["Manage",null,"/ˈmænɪdʒ/","menij","мэниж","/ˈmænɪdʒ/","menij","мэниж","Справляться","Uddalamoq"],
  ["Skin",null,"/skɪn/","skin","скин","/skɪn/","skin","скин","Кожа человека","Odam terisi"],
  ["Later",null,"/ˈleɪtə(r)/","leyta","лэйта","/ˈleɪtɚ/","leydar","лэйдар","Позже","Keyinroq"],
  ["Relative",null,"/ˈrelətɪv/","relativ","рэлатив","/ˈrelətɪv/","reladiv","рэладив","Родственник","Qarindosh"],
  ["Pilot",null,"/ˈpaɪlət/","paylat","пайлат","/ˈpaɪlət/","paylat","пайлат","Пилот","Uchuvchi"],
  ["Crash",null,"/kræʃ/","kresh","крэш","/kræʃ/","kresh","крэш","Авария","Avariyaga uchramoq"],
  ["Island",null,"/ˈaɪlənd/","ayland","айланд","/ˈaɪlənd/","ayland","айланд","Остров","Orol"],
  ["Horrible",null,"/ˈhɒrəbl/","horibl","хорибл","/ˈhɔːrəbəl/","hoorabl","хоорабл","Страшный","Dahshatli"],
  ["Tongue",null,"/tʌŋ/","tang","танг","/tʌŋ/","tang","танг","Язык","Til"],
  ["Lizard",null,"/ˈlɪzəd/","lizad","лизад","/ˈlɪzɚd/","lizard","лизард","Ящерица","Kaltakesak"],
  ["Include",null,"/ɪnˈkluːd/","inkluud","инклууд","/ɪnˈkluːd/","inkluud","инклууд","Содержать","O'z ichiga olmoq"],
  ["Research",null,"/rɪˈsɜːtʃ/","risyoch","рисёч","/ˈriːsɝːtʃ/","riisyorch","риисёрч","Исследование","Tadqiqot"],
  ["Find out",null,"/ˌfaɪnd ˈaʊt/","faynd aut","файнд аут","/ˌfaɪnd ˈaʊt/","faynd aut","файнд аут","Выяснить","Bilib olmoq"]
 ]}
];
